
import type { Question } from './types';

export const newEnglishLevel8Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zeal' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'ঘৃণা', isCorrect: false },
      { text: 'প্রবল আগ্রহ বা উৎসাহ', isCorrect: true },
      { text: 'অলসতা', isCorrect: false },
      { text: 'ভয়', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/jiːld/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত (IPA)?",
    answers: [
      { text: 'Yield', isCorrect: true },
      { text: 'Yell', isCorrect: false },
      { text: 'Zeal', isCorrect: false },
      { text: 'Zone', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zombie' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈzɒmbi/', isCorrect: true },
      { text: '/ˈzəʊn/', isCorrect: false },
      { text: '/ˈziːl/', isCorrect: false },
      { text: '/ˈjel/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yell' শব্দটির সঠিক বাংলা অর্থ কী?",
    answers: [
      { text: 'চুপিচুপি বলা', isCorrect: false },
      { text: 'চিৎকার করা', isCorrect: true },
      { text: 'হাসা', isCorrect: false },
      { text: 'কান্না করা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ˈze lət/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Zealot', isCorrect: true },
      { text: 'Zealous', isCorrect: false },
      { text: 'Zeal', isCorrect: false },
      { text: 'Zone', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zone' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'পাহাড়', isCorrect: false },
      { text: 'অঞ্চল বা এলাকা', isCorrect: true },
      { text: 'সমুদ্র', isCorrect: false },
      { text: 'আকাশ', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zealous' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈze ləs/', isCorrect: true },
      { text: '/ˈze lət/', isCorrect: false },
      { text: '/ziːl/', isCorrect: false },
      { text: '/ˈzɒm bi/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ˈjɑː hu/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Yahoo', isCorrect: true },
      { text: 'Yacht', isCorrect: false },
      { text: 'Yield', isCorrect: false },
      { text: 'Yell', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yacht' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'ছোট জাহাজ বা প্রমোদতরি', isCorrect: true },
      { text: 'বাস', isCorrect: false },
      { text: 'রিকশা', isCorrect: false },
      { text: 'উড়োজাহাজ', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yield' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/jiːld/', isCorrect: true },
      { text: '/jel/', isCorrect: false },
      { text: '/ziːl/', isCorrect: false },
      { text: '/zəʊn/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zealot' শব্দটির অর্থ কী?",
    answers: [
      { text: 'অতি গোঁড়া বা ধর্মান্ধ ব্যক্তি', isCorrect: true },
      { text: 'উদার ব্যক্তি', isCorrect: false },
      { text: 'বিজ্ঞানী', isCorrect: false },
      { text: 'চিকিৎসক', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/zuː/ এটি নিচের কোন স্থানের সঠিক IPA?",
    answers: [
      { text: 'Zoo', isCorrect: true },
      { text: 'Zone', isCorrect: false },
      { text: 'Zeal', isCorrect: false },
      { text: 'Zip', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yahoo' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈjɑːhu/', isCorrect: true },
      { text: '/jɒt/', isCorrect: false },
      { text: '/jiːld/', isCorrect: false },
      { text: '/ˈzelət/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zoo' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'চিড়িয়াখানা', isCorrect: true },
      { text: 'বিদ্যালয়', isCorrect: false },
      { text: 'বাজার', isCorrect: false },
      { text: 'বাগান', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/jel/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Yell', isCorrect: true },
      { text: 'Yield', isCorrect: false },
      { text: 'Zeal', isCorrect: false },
      { text: 'Yacht', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zealous' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'অতি উৎসাহী', isCorrect: true },
      { text: 'অত্যন্ত রাগী', isCorrect: false },
      { text: 'খুব দুঃখিত', isCorrect: false },
      { text: 'ভীতু', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yacht' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/jɒt/', isCorrect: true },
      { text: '/jɑːt/', isCorrect: false },
      { text: '/jiːld/', isCorrect: false },
      { text: '/jel/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/zəʊn/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Zone', isCorrect: true },
      { text: 'Zoo', isCorrect: false },
      { text: 'Zeal', isCorrect: false },
      { text: 'Zip', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yield' বলতে কী বোঝায়?",
    answers: [
      { text: 'বশ্যতা স্বীকার করা / উৎপাদন', isCorrect: true },
      { text: 'অস্বীকার করা', isCorrect: false },
      { text: 'ধ্বংস করা', isCorrect: false },
      { text: 'চুরি করা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zeal' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ziːl/', isCorrect: true },
      { text: '/ˈzeləs/', isCorrect: false },
      { text: '/ˈzelət/', isCorrect: false },
      { text: '/zuː/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Zombie' এর অর্থ কী?",
    answers: [
      { text: 'মৃতদেহ যা পুনরায় জীবিত হয়েছে', isCorrect: true },
      { text: 'একজন বীর', isCorrect: false },
      { text: 'মহাকাশচারী', isCorrect: false },
      { text: 'শিক্ষক', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ˈziːl/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Zeal', isCorrect: true },
      { text: 'Zealot', isCorrect: false },
      { text: 'Zealous', isCorrect: false },
      { text: 'Zone', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yahoo' শব্দটির অর্থ কী?",
    answers: [
      { text: 'অসভ্য বা বন্য ব্যক্তি', isCorrect: true },
      { text: 'অত্যন্ত ভদ্র লোক', isCorrect: false },
      { text: 'রাজা', isCorrect: false },
      { text: 'বন্ধু', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Yell' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/jel/', isCorrect: true },
      { text: '/jiːld/', isCorrect: false },
      { text: '/jɒt/', isCorrect: false },
      { text: '/zuː/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ɪn ˈsep tə bl/ এটি কোন শব্দের IPA (ফাইল থেকে)?",
    answers: [
      { text: 'Inacceptable', isCorrect: true },
      { text: 'Innocent', isCorrect: false },
      { text: 'Inside', isCorrect: false },
      { text: 'Income', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Acceptable' শব্দটির বিপরীত শব্দ কোনটি হতে পারে (A2/B2 লেভেল অনুযায়ী)?",
    answers: [
      { text: 'Unacceptable', isCorrect: true },
      { text: 'Accept', isCorrect: false },
      { text: 'Achieving', isCorrect: false },
      { text: 'Actual', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ˈæktɪvɪst/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Activist', isCorrect: true },
      { text: 'Activity', isCorrect: false },
      { text: 'Activate', isCorrect: false },
      { text: 'Actor', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Achievement' শব্দটির সঠিক অর্থ কী?",
    answers: [
      { text: 'অর্জন', isCorrect: true },
      { text: 'বর্জন', isCorrect: false },
      { text: 'পরাজয়', isCorrect: false },
      { text: 'লজ্জা', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "/ə ˈtʃiːv/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Achieve', isCorrect: true },
      { text: 'Achievement', isCorrect: false },
      { text: 'Acid', isCorrect: false },
      { text: 'Acre', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "'Ability' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/əˈbɪləti/', isCorrect: true },
      { text: '/ˈeɪbl/', isCorrect: false },
      { text: '/ˈæsɪd/', isCorrect: false },
      { text: '/ækt/', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'You must be ________ to speak French for this job.',
    answers: [
      { text: 'able', isCorrect: true },
      { text: 'ably', isCorrect: false },
      { text: 'ability', isCorrect: false },
      { text: 'enable', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'We were ________ assisted by a team of volunteers.',
    answers: [
      { text: 'able', isCorrect: false },
      { text: 'ably', isCorrect: true },
      { text: 'ability', isCorrect: false },
      { text: 'unable', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'People with the disease may lose their ________ to communicate.',
    answers: [
      { text: 'able', isCorrect: false },
      { text: 'ably', isCorrect: false },
      { text: 'ability', isCorrect: true },
      { text: 'enable', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'This new programme will ________ older people to study at college.',
    answers: [
      { text: 'able', isCorrect: false },
      { text: 'ability', isCorrect: false },
      { text: 'enable', isCorrect: true },
      { text: 'disable', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'Some families suffer because of their ________ to pay.',
    answers: [
      { text: 'unable', isCorrect: false },
      { text: 'inability', isCorrect: true },
      { text: 'disable', isCorrect: false },
      { text: 'ably', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'He made his position ________ clear.',
    answers: [
      { text: 'absolute', isCorrect: false },
      { text: 'absolutely', isCorrect: true },
      { text: 'absoluteness', isCorrect: false },
      { text: 'absolve', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'The car ________ to overtake me.',
    answers: [
      { text: 'accelerate', isCorrect: false },
      { text: 'accelerated', isCorrect: true },
      { text: 'acceleration', isCorrect: false },
      { text: 'decelerate', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'We have seen an ________ in the rate of economic growth.',
    answers: [
      { text: 'accelerate', isCorrect: false },
      { text: 'accelerating', isCorrect: false },
      { text: 'acceleration', isCorrect: true },
      { text: 'accelerative', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'It was pouring with rain, so I ________ his offer of a lift.',
    answers: [
      { text: 'accept', isCorrect: false },
      { text: 'accepted', isCorrect: true },
      { text: 'acceptable', isCorrect: false },
      { text: 'acceptance', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'Children must learn socially ________ behaviour.',
    answers: [
      { text: 'accept', isCorrect: false },
      { text: 'acceptable', isCorrect: true },
      { text: 'acceptation', isCorrect: false },
      { text: 'acceptably', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'Please confirm your ________ of this offer in writing.',
    answers: [
      { text: 'accept', isCorrect: false },
      { text: 'acceptable', isCorrect: false },
      { text: 'acceptance', isCorrect: true },
      { text: 'acceptably', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'The ________ of the data is very important.',
    answers: [
      { text: 'accurate', isCorrect: false },
      { text: 'accurately', isCorrect: false },
      { text: 'accuracy', isCorrect: true },
      { text: 'inaccurate', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'The report ________ describes the current situation.',
    answers: [
      { text: 'accurate', isCorrect: false },
      { text: 'accurately', isCorrect: true },
      { text: 'accuracy', isCorrect: false },
      { text: 'inaccuracy', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'The computer system has been ________.',
    answers: [
      { text: 'active', isCorrect: false },
      { text: 'activate', isCorrect: false },
      { text: 'activated', isCorrect: true },
      { text: 'activist', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'She takes an ________ part in local politics.',
    answers: [
      { text: 'active', isCorrect: true },
      { text: 'activity', isCorrect: false },
      { text: 'activate', isCorrect: false },
      { text: 'actively', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'He is a political ________ who works for social change.',
    answers: [
      { text: 'active', isCorrect: false },
      { text: 'activity', isCorrect: false },
      { text: 'activist', isCorrect: true },
      { text: 'activate', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'The school offers a wide range of extracurricular ________.',
    answers: [
      { text: 'active', isCorrect: false },
      { text: 'activities', isCorrect: true },
      { text: 'actively', isCorrect: false },
      { text: 'activist', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'What is the ________ cost of the repair?',
    answers: [
      { text: 'actual', isCorrect: true },
      { text: 'actually', isCorrect: false },
      { text: 'actuality', isCorrect: false },
      { text: 'actualize', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "We've ________ spoken to him about the problem.",
    answers: [
      { text: 'actual', isCorrect: false },
      { text: 'actually', isCorrect: true },
      { text: 'actualize', isCorrect: false },
      { text: 'actualist', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "It's an ________ story about his travels.",
    answers: [
      { text: 'amuse', isCorrect: false },
      { text: 'amusing', isCorrect: true },
      { text: 'amusement', isCorrect: false },
      { text: 'amusedly', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'She ________ the children with her stories.',
    answers: [
      { text: 'amuse', isCorrect: false },
      { text: 'amused', isCorrect: true },
      { text: 'amusing', isCorrect: false },
      { text: 'amusement', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'The ________ of the project was very detailed.',
    answers: [
      { text: 'analyze', isCorrect: false },
      { text: 'analysis', isCorrect: true },
      { text: 'analyst', isCorrect: false },
      { text: 'analytical', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'We need to ________ the results of the survey.',
    answers: [
      { text: 'analyze', isCorrect: true },
      { text: 'analysis', isCorrect: false },
      { text: 'analyst', isCorrect: false },
      { text: 'analytical', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'He is a financial ________ for a large bank.',
    answers: [
      { text: 'analyze', isCorrect: false },
      { text: 'analysis', isCorrect: false },
      { text: 'analyst', isCorrect: true },
      { text: 'analytically', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'She has a very ________ mind.',
    answers: [
      { text: 'analyze', isCorrect: false },
      { text: 'analysis', isCorrect: false },
      { text: 'analyst', isCorrect: false },
      { text: 'analytical', isCorrect: true },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'I have an ________ to see the doctor.',
    answers: [
      { text: 'appoint', isCorrect: false },
      { text: 'appointment', isCorrect: true },
      { text: 'appointed', isCorrect: false },
      { text: 'appointee', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'A committee has been ________ to investigate the matter.',
    answers: [
      { text: 'appoint', isCorrect: false },
      { text: 'appointed', isCorrect: true },
      { text: 'appointment', isCorrect: false },
      { text: 'appointee', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'I really ________ your help.',
    answers: [
      { text: 'appreciate', isCorrect: true },
      { text: 'appreciation', isCorrect: false },
      { text: 'appreciative', isCorrect: false },
      { text: 'appreciatively', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'The audience was very ________ of the performance.',
    answers: [
      { text: 'appreciate', isCorrect: false },
      { text: 'appreciation', isCorrect: false },
      { text: 'appreciative', isCorrect: true },
      { text: 'appreciatively', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'It would be ________ to comment on the situation.',
    answers: [
      { text: 'wise', isCorrect: false },
      { text: 'wisely', isCorrect: false },
      { text: 'unwise', isCorrect: true },
      { text: 'wisdom', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'She nodded ________ as I spoke.',
    answers: [
      { text: 'wise', isCorrect: false },
      { text: 'wisely', isCorrect: true },
      { text: 'wisdom', isCorrect: false },
      { text: 'unwisely', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'She was known to be a woman of great ________.',
    answers: [
      { text: 'wise', isCorrect: false },
      { text: 'wisely', isCorrect: false },
      { text: 'wisdom', isCorrect: true },
      { text: 'unwise', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: "I'm sure we can come to some ________ arrangement.",
    answers: [
      { text: 'work', isCorrect: false },
      { text: 'workable', isCorrect: true },
      { text: 'working', isCorrect: false },
      { text: 'overworked', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'The kids always ________ hard at school.',
    answers: [
      { text: 'work', isCorrect: true },
      { text: 'workable', isCorrect: false },
      { text: 'working', isCorrect: false },
      { text: 'workforce', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'Have you been ________ recently? You look tired.',
    answers: [
      { text: 'work', isCorrect: false },
      { text: 'overworking', isCorrect: true },
      { text: 'workable', isCorrect: false },
      { text: 'world', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'The show has a ________ audience.',
    answers: [
      { text: 'world', isCorrect: false },
      { text: 'worldwide', isCorrect: true },
      { text: 'worldly', isCorrect: false },
      { text: 'worldliness', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'She was ________ for the job by her experience.',
    answers: [
      { text: 'qualify', isCorrect: false },
      { text: 'qualified', isCorrect: true },
      { text: 'qualification', isCorrect: false },
      { text: 'disqualification', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'What ________ do you need for this position?',
    answers: [
      { text: 'qualify', isCorrect: false },
      { text: 'qualifying', isCorrect: false },
      { text: 'qualifications', isCorrect: true },
      { text: 'qualifier', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'She ________ for the finals last week.',
    answers: [
      { text: 'qualify', isCorrect: false },
      { text: 'qualified', isCorrect: true },
      { text: 'qualification', isCorrect: false },
      { text: 'quality', isCorrect: false },
    ],
  },
  {
    level: '0.8',
    subject: 'English',
    questionText: 'The ________ of the air in the city is very poor.',
    answers: [
      { text: 'qualify', isCorrect: false },
      { text: 'quality', isCorrect: true },
      { text: 'qualitative', isCorrect: false },
      { text: 'qualified', isCorrect: false },
    ],
  },
];

    