import type { Question } from './types';

export const newEnglishLevel7Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Abundant' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'অভাব', isCorrect: false },
      { text: 'প্রচুর/বিপুল', isCorrect: true },
      { text: 'সামান্য', isCorrect: false },
      { text: 'উজ্জ্বল', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/əˈbæn dən/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত (IPA)?",
    answers: [
      { text: 'Abandon', isCorrect: true },
      { text: 'Abundant', isCorrect: false },
      { text: 'Ability', isCorrect: false },
      { text: 'Absence', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Accurate' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈæ kjə rət/', isCorrect: true },
      { text: '/ək ˈsept/', isCorrect: false },
      { text: '/ə ˈkjuːt/', isCorrect: false },
      { text: '/ə ˈtʃiːv/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Brilliant' শব্দটির বাংলা অর্থ কী?",
    answers: [
      { text: 'সাহসী', isCorrect: false },
      { text: 'মেধাবী/উজ্জ্বল', isCorrect: true },
      { text: 'ধূর্ত', isCorrect: false },
      { text: 'অলস', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ɪˈnʌf/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Enough', isCorrect: true },
      { text: 'Energy', isCorrect: false },
      { text: 'Entry', isCorrect: false },
      { text: 'Enjoy', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Exaggerate' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'সংক্ষিপ্ত করা', isCorrect: false },
      { text: 'বাড়িয়ে বলা', isCorrect: true },
      { text: 'বর্ণনা করা', isCorrect: false },
      { text: 'গোপন করা', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Knowledge' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈnɒl ɪdʒ/', isCorrect: true },
      { text: '/nəʊ/', isCorrect: false },
      { text: '/ˈknɒ lɪdʒ/', isCorrect: false },
      { text: '/ˈnəʊ lɪdʒ/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˌriː ə ˈʃʊə(r)/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Reassure', isCorrect: true },
      { text: 'Reason', isCorrect: false },
      { text: 'Recent', isCorrect: false },
      { text: 'Record', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Insufficient' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'পর্যাপ্ত', isCorrect: false },
      { text: 'অপ্রাসঙ্গিক', isCorrect: false },
      { text: 'অপর্যাপ্ত', isCorrect: true },
      { text: 'অদৃশ্য', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Wrist' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/rɪst/', isCorrect: true },
      { text: '/rɪstɪ/', isCorrect: false },
      { text: '/wrɪst/', isCorrect: false },
      { text: '/raɪst/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Yearn' শব্দটির অর্থ কী?",
    answers: [
      { text: 'উপার্জন করা', isCorrect: false },
      { text: 'ব্যাকুল আকাঙ্ক্ষা করা', isCorrect: true },
      { text: 'ঘৃণা করা', isCorrect: false },
      { text: 'ভুলে যাওয়া', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˈjɒ ɡət/ এটি নিচের কোন খাবারের সঠিক IPA?",
    answers: [
      { text: 'Yogurt', isCorrect: true },
      { text: 'Yellow', isCorrect: false },
      { text: 'Yeast', isCorrect: false },
      { text: 'Yawn', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Worthy' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwɜː(r) ði/', isCorrect: true },
      { text: '/ˈwɜː r θi/', isCorrect: false },
      { text: '/wɜː(r) θ/', isCorrect: false },
      { text: '/ˈwɜː r kɪŋ/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Irrelevant' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'প্রাসঙ্গিক', isCorrect: false },
      { text: 'অপ্রাসঙ্গিক', isCorrect: true },
      { text: 'অকেজো', isCorrect: false },
      { text: 'অবৈধ', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ɪ ˈkwɪp mənt/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Equipment', isCorrect: true },
      { text: 'Equal', isCorrect: false },
      { text: 'Entry', isCorrect: false },
      { text: 'Event', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Fragile' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'মজবুত', isCorrect: false },
      { text: 'ভঙ্গুর', isCorrect: true },
      { text: 'পাতলা', isCorrect: false },
      { text: 'দামি', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Drought' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/draʊt/', isCorrect: true },
      { text: '/drɔːt/', isCorrect: false },
      { text: '/drʌf/', isCorrect: false },
      { text: '/draʊθ/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˌkɒm prə ˈmaɪz/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Compromise', isCorrect: true },
      { text: 'Comprise', isCorrect: false },
      { text: 'Company', isCorrect: false },
      { text: 'Compare', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Wrinkle' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'ভাঁজ বা কুঁচকানো', isCorrect: true },
      { text: 'সোজা করা', isCorrect: false },
      { text: 'পরিষ্কার', isCorrect: false },
      { text: 'উজ্জ্বল', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Youth' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/juːθ/', isCorrect: true },
      { text: '/jʊθ/', isCorrect: false },
      { text: '/juːs/', isCorrect: false },
      { text: '/jʌŋ/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Obvious' শব্দটির বাংলা অর্থ কী?",
    answers: [
      { text: 'অস্পষ্ট', isCorrect: false },
      { text: 'স্পষ্ট/প্রতীয়মান', isCorrect: true },
      { text: 'কঠিন', isCorrect: false },
      { text: 'সাধারণ', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˈpɜː(r) tʃəs/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Purchase', isCorrect: true },
      { text: 'Purpose', isCorrect: false },
      { text: 'Perfect', isCorrect: false },
      { text: 'Person', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Queue' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/kjuː/', isCorrect: true },
      { text: '/kwɪ/', isCorrect: false },
      { text: '/kwe/', isCorrect: false },
      { text: '/kjuːi/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Sufficient' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'পর্যাপ্ত', isCorrect: true },
      { text: 'অতিরিক্ত', isCorrect: false },
      { text: 'সামান্য', isCorrect: false },
      { text: 'অভাব', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ə ˈpɪə rəns/ এটি কোন শব্দের IPA?",
    answers: [
      { text: 'Appearance', isCorrect: true },
      { text: 'Appoint', isCorrect: false },
      { text: 'Approve', isCorrect: false },
      { text: 'Appeal', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Leisure' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'কাজ', isCorrect: false },
      { text: 'অবসর', isCorrect: true },
      { text: 'আনন্দ', isCorrect: false },
      { text: 'ভ্রমণ', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˈmɪs tʃɪf/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Mischief', isCorrect: true },
      { text: 'Machine', isCorrect: false },
      { text: 'Message', isCorrect: false },
      { text: 'Music', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Precious' শব্দটির সঠিক অর্থ কী?",
    answers: [
      { text: 'সস্তা', isCorrect: false },
      { text: 'মূল্যবান', isCorrect: true },
      { text: 'পুরাতন', isCorrect: false },
      { text: 'সাধারণ', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "/ˌvɒl ən ˈtɪə(r)/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Volunteer', isCorrect: true },
      { text: 'Volume', isCorrect: false },
      { text: 'Victory', isCorrect: false },
      { text: 'Village', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: "'Yard' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/jɑː(r)d/', isCorrect: true },
      { text: '/jærd/', isCorrect: false },
      { text: '/jɜːrd/', isCorrect: false },
      { text: '/jɔːrd/', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"He goes to school every day." - এর সঠিক বাংলা অনুবাদ কোনটি?',
    answers: [
      { text: 'সে প্রতিদিন স্কুলে গিয়েছিল', isCorrect: false },
      { text: 'সে প্রতিদিন স্কুলে যায়', isCorrect: true },
      { text: 'সে স্কুলে যাচ্ছে', isCorrect: false },
      { text: 'সে স্কুলে যাবে', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"রৌদ্রে দৌড়াদৌড়ি করিও না।" - এর ইংরেজি অনুবাদ কোনটি?',
    answers: [
      { text: 'Do not run in the sun', isCorrect: true },
      { text: 'Do not walk in the sun', isCorrect: false },
      { text: 'Run in the sun', isCorrect: false },
      { text: 'Do not run at night', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"Diamond is very valuable." - বাক্যটির অর্থ কী?',
    answers: [
      { text: 'হীরা খুব সস্তা', isCorrect: false },
      { text: 'হীরা খুবই মূল্যবান', isCorrect: true },
      { text: 'হীরা খুব শক্ত', isCorrect: false },
      { text: 'সোনা খুব মূল্যবান', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"সে কোমলভাবে আমার নাম জিজ্ঞাসা করেছিল।" - এর সঠিক ইংরেজি কোনটি?',
    answers: [
      { text: 'He asked my name loudly', isCorrect: false },
      { text: 'He asked my name gently', isCorrect: true },
      { text: 'He said my name', isCorrect: false },
      { text: 'He asks my name', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"She walks slowly." - এর বাংলা অর্থ কী?',
    answers: [
      { text: 'সে দ্রুত হাঁটে', isCorrect: false },
      { text: 'সে ধীরে হাঁটে', isCorrect: true },
      { text: 'সে দৌড়াচ্ছে', isCorrect: false },
      { text: 'সে বসে আছে', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"হাঁটা সর্বোত্তম ব্যায়াম।" - এর সঠিক ইংরেজি অনুবাদ কোনটি?',
    answers: [
      { text: 'Running is good', isCorrect: false },
      { text: 'Walking is the best exercise', isCorrect: true },
      { text: 'Eat well', isCorrect: false },
      { text: 'Exercise is good', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"We should take care of our children." - বাক্যটির অর্থ কী?',
    answers: [
      { text: 'শিশুদের মারা উচিত', isCorrect: false },
      { text: 'আমাদের বাচ্চাদের যত্ন নেওয়া উচিত', isCorrect: true },
      { text: 'বাচ্চারা খেলছে', isCorrect: false },
      { text: 'যত্ন নিও না', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"তার তিনটি লাল কলম আছে।" - এর ইংরেজি অনুবাদ কোনটি?',
    answers: [
      { text: 'He has three red pens', isCorrect: true },
      { text: 'He had red pens', isCorrect: false },
      { text: 'I have red pens', isCorrect: false },
      { text: 'He has blue pens', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"It is likely to rain here." - এর সঠিক বাংলা অনুবাদ কোনটি?',
    answers: [
      { text: 'এখানে বৃষ্টি হতে পারে', isCorrect: true },
      { text: 'এখানে বৃষ্টি হচ্ছে', isCorrect: false },
      { text: 'বৃষ্টি হবে না', isCorrect: false },
      { text: 'বৃষ্টি হয়েছিল', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"সে একজন সৎ লোক।" - এর ইংরেজি অনুবাদ কোনটি?',
    answers: [
      { text: 'He is an honest man', isCorrect: true },
      { text: 'He is a bad man', isCorrect: false },
      { text: 'He was honest', isCorrect: false },
      { text: 'I am honest', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"I cannot resist learning English." - এর অর্থ কী?',
    answers: [
      { text: 'আমি ইংরেজি শিখতে পারি না', isCorrect: false },
      { text: 'আমি ইংরেজি না শিখে থাকতে পারি না', isCorrect: true },
      { text: 'ইংরেজি শেখা কঠিন', isCorrect: false },
      { text: 'আমি ইংরেজি শিখব', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"সময় অপচয় করা ঠিক নয়।" - এর ইংরেজি কোনটি?',
    answers: [
      { text: 'Do not waste time', isCorrect: false },
      { text: 'It is no use wasting time', isCorrect: true },
      { text: 'Time is gold', isCorrect: false },
      { text: 'Waste your time', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"I am yet to go to market." - এর বাংলা অর্থ কী?',
    answers: [
      { text: 'আমি বাজারে গিয়েছি', isCorrect: false },
      { text: 'আমার এখনো বাজারে যাওয়া হয়নি', isCorrect: true },
      { text: 'আমি বাজারে যাব', isCorrect: false },
      { text: 'বাজারে যেও না', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"তুমি কি ইংরেজি শিখেছিলে?" - এর সঠিক ইংরেজি কোনটি?',
    answers: [
      { text: 'Did you learn English?', isCorrect: true },
      { text: 'Do you learn English?', isCorrect: false },
      { text: 'Will you learn English?', isCorrect: false },
      { text: 'You learned English', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"Kuwait is a Muslim country." - বাক্যটির অর্থ কী?',
    answers: [
      { text: 'কুয়েত একটি সুন্দর দেশ', isCorrect: false },
      { text: 'কুয়েত একটি মুসলিম রাষ্ট্র', isCorrect: true },
      { text: 'কুয়েত অনেক বড়', isCorrect: false },
      { text: 'কুয়েত ধনি দেশ', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"আমি তোমার সাথে কথা না বলে থাকতে পারি না।" - এর ইংরেজি কী?',
    answers: [
      { text: 'I cannot resist talking to you', isCorrect: true },
      { text: 'I will not talk', isCorrect: false },
      { text: 'I talk to you', isCorrect: false },
      { text: 'I can talk', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"It is no use sleeping now." - এর সঠিক বাংলা কোনটি?',
    answers: [
      { text: 'এখন ঘুমানোর সময়', isCorrect: false },
      { text: 'এখন ঘুমিয়ে কোনো লাভ নেই', isCorrect: true },
      { text: 'এখন ঘুমিও না', isCorrect: false },
      { text: 'আমি ঘুমাব', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"আমরা আজ পুকুরে মাছ ধরতে পারি।" - এর ইংরেজি অনুবাদ কোনটি?',
    answers: [
      { text: 'Today we are likely to catch fish in the pond', isCorrect: true },
      { text: 'We catch fish', isCorrect: false },
      { text: 'Fish is in pond', isCorrect: false },
      { text: 'Catch fish today', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"He is sick." - এর বাংলা অর্থ কী?',
    answers: [
      { text: 'সে অসুস্থ', isCorrect: true },
      { text: 'সে সুস্থ', isCorrect: false },
      { text: 'সে আসছে', isCorrect: false },
      { text: 'সে খেলে', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"Safi is yet to come." - এর অর্থ কী?',
    answers: [
      { text: 'সাফি এসেছে', isCorrect: false },
      { text: 'সাফির আসা এখনো বাকি', isCorrect: true },
      { text: 'সাফি আসবে', isCorrect: false },
      { text: 'সাফি আসেনি', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"সে আমাকে এক গ্লাস পানি দিয়েছিল।" - এর ইংরেজি অনুবাদ কোনটি?',
    answers: [
      { text: 'He gave me a glass of water', isCorrect: true },
      { text: 'Give me water', isCorrect: false },
      { text: 'I want water', isCorrect: false },
      { text: 'He gives water', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"We play cricket." - বাক্যটির অর্থ কী?',
    answers: [
      { text: 'আমরা ক্রিকেট খেলব', isCorrect: false },
      { text: 'আমরা ক্রিকেট খেলি', isCorrect: true },
      { text: 'তারা ক্রিকেট খেলে', isCorrect: false },
      { text: 'ক্রিকেট ভালো খেলা', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"সে স্কুলে পছন্দ করে না।" - এর ইংরেজি কোনটি?',
    answers: [
      { text: 'He does not like to go to school', isCorrect: true },
      { text: 'He likes school', isCorrect: false },
      { text: 'He goes to school', isCorrect: false },
      { text: 'School is bad', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"Ashik eats rice." - এর বাংলা অর্থ কী?',
    answers: [
      { text: 'আশিক ভাত খাচ্ছে', isCorrect: false },
      { text: 'আশিক ভাত খায়', isCorrect: true },
      { text: 'আশিক ভাত খাবে', isCorrect: false },
      { text: 'সে ভাত খায়', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"Naima is a beautiful girl." - এর সঠিক বাংলা অনুবাদ কী?',
    answers: [
      { text: 'নাইমা একজন ভালো মেয়ে', isCorrect: false },
      { text: 'নাইমা একজন সুন্দর মেয়ে', isCorrect: true },
      { text: 'নাইমা বুদ্ধিমতী', isCorrect: false },
      { text: 'সে সুন্দর', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"মিথ্যা বলা মহাপাপ।" - এর ইংরেজি অনুবাদ কোনটি?',
    answers: [
      { text: 'To tell a lie is a great sin', isCorrect: true },
      { text: 'Lie is bad', isCorrect: false },
      { text: 'Do not lie', isCorrect: false },
      { text: 'Telling lie is easy', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"It is likely to happen." - এর অর্থ কী?',
    answers: [
      { text: 'এটি ঘটার সম্ভাবনা আছে', isCorrect: true },
      { text: 'এটি ঘটেছে', isCorrect: false },
      { text: 'এটি ঘটবে না', isCorrect: false },
      { text: 'এটি হতে দাও', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"আমার মা অসুস্থ।" - এর ইংরেজি অনুবাদ কোনটি?',
    answers: [
      { text: 'My mother is sick', isCorrect: true },
      { text: 'Mother is fine', isCorrect: false },
      { text: 'I am sick', isCorrect: false },
      { text: 'My mom is happy', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"He writes a letter." - বাক্যটির অর্থ কী?',
    answers: [
      { text: 'সে একটি চিঠি লিখেছিল', isCorrect: false },
      { text: 'সে একটি চিঠি লেখে', isCorrect: true },
      { text: 'সে চিঠি লিখছে', isCorrect: false },
      { text: 'আমি চিঠি লিখি', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"মানুষ মরণশীল।" - এর ইংরেজি কোনটি?',
    answers: [
      { text: 'Man is mortal', isCorrect: true },
      { text: 'Man is good', isCorrect: false },
      { text: 'Man will die', isCorrect: false },
      { text: 'Human is mortal', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"I cannot resist loving my Mom." - এর অর্থ কী?',
    answers: [
      { text: 'আমি আমার মাকে না ভালোবেসে থাকতে পারি না', isCorrect: true },
      { text: 'আমি মাকে ভালোবাসি', isCorrect: false },
      { text: 'মা আমাকে ভালোবাসেন', isCorrect: false },
      { text: 'মাকে ভালোবাসা উচিত', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"এখন বই কেনা বৃথা।" - এর ইংরেজি কোনটি?',
    answers: [
      { text: 'It is no use buying the book', isCorrect: true },
      { text: 'Buy the book', isCorrect: false },
      { text: 'Do not buy book', isCorrect: false },
      { text: 'Book is use', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"সে কি কলেজে গিয়েছিল?" - এর ইংরেজি কী?',
    answers: [
      { text: 'Did he go to college?', isCorrect: true },
      { text: 'Does he go to college?', isCorrect: false },
      { text: 'He went to college', isCorrect: false },
      { text: 'Was he in college?', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"Nusrat helped the poor." - এর বাংলা অনুবাদ কী?',
    answers: [
      { text: 'নুসরাত গরিবদের সাহায্য করে', isCorrect: false },
      { text: 'নুসরাত গরিবদের সাহায্য করেছিল', isCorrect: true },
      { text: 'গরিবদের সাহায্য করো', isCorrect: false },
      { text: 'সে গরিব', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"তারা এখনো শুরু করেনি।" - এর ইংরেজি কোনটি?',
    answers: [
      { text: 'They are yet to start', isCorrect: true },
      { text: 'They start now', isCorrect: false },
      { text: 'They have started', isCorrect: false },
      { text: 'Do not start', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"Walking is good for health." - এর অর্থ কী?',
    answers: [
      { text: 'হাঁটা স্বাস্থ্যের জন্য ভালো', isCorrect: true },
      { text: 'শরীর ভালো রাখো', isCorrect: false },
      { text: 'আমি হাঁটছি', isCorrect: false },
      { text: 'ব্যায়াম করো', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"আমি আজ ভাত খাব না।" - এর ইংরেজি কী?',
    answers: [
      { text: 'I will not eat rice today', isCorrect: true },
      { text: 'I do not eat rice', isCorrect: false },
      { text: 'I ate rice', isCorrect: false },
      { text: 'No rice today', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"He is an intelligent boy." - এর বাংলা কী?',
    answers: [
      { text: 'সে একজন বুদ্ধিমান ছেলে', isCorrect: true },
      { text: 'সে একজন ভালো ছেলে', isCorrect: false },
      { text: 'ছেলেটি সৎ', isCorrect: false },
      { text: 'সে ছাত্র', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"সূর্য পূর্ব দিকে ওঠে।" - এর ইংরেজি অনুবাদ কোনটি?',
    answers: [
      { text: 'The sun rises in the east', isCorrect: true },
      { text: 'Sun is in east', isCorrect: false },
      { text: 'Sun rises', isCorrect: false },
      { text: 'East is the sun', isCorrect: false },
    ],
  },
  {
    level: '0.7',
    subject: 'English',
    questionText: '"We are likely to go to Dhaka." - এর অর্থ কী?',
    answers: [
      { text: 'আমাদের ঢাকা যাওয়ার সম্ভাবনা আছে', isCorrect: true },
      { text: 'আমরা ঢাকা গিয়েছি', isCorrect: false },
      { text: 'ঢাকা চলো', isCorrect: false },
      { text: 'আমরা ঢাকা যাব না', isCorrect: false },
    ],
  },
];
