import type { Question } from './types';

export const newEnglishLevel0Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/e/” ধ্বনিটির বাংলা সমতুল্য ধ্বনি কী?',
    answers: [
      { text: '/ ই /', isCorrect: false },
      { text: '/ এ /', isCorrect: true },
      { text: '/ অ্যা/ ', isCorrect: false },
      { text: '/ আ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ɒ/” ধ্বনিটির বাংলা সমতুল্য ধ্বনি কী?',
    answers: [
      { text: '/ এ /', isCorrect: false },
      { text: '/ অ্যা/ ', isCorrect: false },
      { text: '/ আ /', isCorrect: false },
      { text: '/ অ /', isCorrect: true },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/æ/” ধ্বনিটির বাংলা সমতুল্য ধ্বনি কী?',
    answers: [
      { text: '/ অ্যা/ ', isCorrect: true },
      { text: '/ আ /', isCorrect: false },
      { text: '/ অ /', isCorrect: false },
      { text: '/ উ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ɜː/” ধ্বনিটির বাংলা সমতুল্য ধ্বনি কী?',
    answers: [
      { text: '/ ঈː /', isCorrect: false },
      { text: '/ আː /', isCorrect: true },
      { text: '/ উː /', isCorrect: false },
      { text: '/ অː /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ɔː/” ধ্বনিটির বাংলা সমতুল্য ধ্বনি কী?',
    answers: [
      { text: '/ আː /', isCorrect: false },
      { text: '/ অː /', isCorrect: true },
      { text: '/ উː /', isCorrect: false },
      { text: '/ ঈː /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/eɪ/”-এর বাংলা সমতুল্য ধ্বনি কী?',
    answers: [
      { text: '/ আই /', isCorrect: false },
      { text: '/ অই /', isCorrect: false },
      { text: '/ ইআ /', isCorrect: false },
      { text: '/ এই /', isCorrect: true },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ɔɪ/” ধ্বনিটির বাংলা সমতুল্য ধ্বনি কী?',
    answers: [
      { text: '/ এই /', isCorrect: false },
      { text: '/ আই /', isCorrect: false },
      { text: '/ অই /', isCorrect: true },
      { text: '/ ইআ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ʊə/”-এর বাংলা সমতুল্য ধ্বনি কী?',
    answers: [
      { text: '/ এআ /', isCorrect: false },
      { text: '/ উআ /', isCorrect: true },
      { text: '/ ওাউ /', isCorrect: false },
      { text: '/ আউ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ʤ/” ধ্বনিটির বাংলা সমতুল্য ধ্বনি কী?',
    answers: [
      { text: '/ জ্ /', isCorrect: true },
      { text: '/ থ্ /', isCorrect: false },
      { text: '/ দ্ /', isCorrect: false },
      { text: '/ শ্ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ð/” ধ্বনিটির বাংলা সমতুল্য ধ্বনি কী?',
    answers: [
      { text: '/ জ্ /', isCorrect: false },
      { text: '/ থ্ /', isCorrect: false },
      { text: '/ দ্ /', isCorrect: true },
      { text: '/ শ্ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ ইং /” এই ধ্বনিটির IPA কী?',
    answers: [
      { text: '/ʧ/', isCorrect: false },
      { text: '/j/', isCorrect: false },
      { text: '/ŋ/', isCorrect: true },
      { text: '/ʃ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ চ্ /” ধ্বনিটির আইপিএ (IPA) কী?',
    answers: [
      { text: '/ʧ/', isCorrect: true },
      { text: '/j/', isCorrect: false },
      { text: '/ŋ/', isCorrect: false },
      { text: '/ʃ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ ইয়া /” ধ্বনিটির আইপিএ (IPA) কী?',
    answers: [
      { text: '/ʧ/', isCorrect: false },
      { text: '/j/', isCorrect: true },
      { text: '/ŋ/', isCorrect: false },
      { text: '/ʃ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ ঈ /” ধ্বনিটির আইপিএ (IPA) কী?',
    answers: [
      { text: '/iː/', isCorrect: true },
      { text: '/ɑː/', isCorrect: false },
      { text: '/ɔː/', isCorrect: false },
      { text: '/uː/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ ই /” ধ্বনিটির আইপিএ (IPA) কী?',
    answers: [
      { text: '/e/', isCorrect: false },
      { text: '/æ/', isCorrect: false },
      { text: '/I/', isCorrect: true },
      { text: '/ʌ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ ওয়া /” ধ্বনিটির আইপিএ (IPA) কী?',
    answers: [
      { text: '/ʊə/', isCorrect: false },
      { text: '/əʊ/', isCorrect: false },
      { text: '/aʊ/', isCorrect: false },
      { text: '/w/', isCorrect: true },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ স্ /” ধ্বনিটির আইপিএ (IPA) কী?',
    answers: [
      { text: '/s/', isCorrect: true },
      { text: '/z/', isCorrect: false },
      { text: '/ʃ/', isCorrect: false },
      { text: '/ʤ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: "'শ্' ধ্বনিটির জন্য IPA কী?",
    answers: [
      { text: '/s/', isCorrect: false },
      { text: '/z/', isCorrect: false },
      { text: '/ʃ/', isCorrect: true },
      { text: '/ʤ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ এআ /” ধ্বনিটির আইপিএ (IPA) কী?',
    answers: [
      { text: '/eɪ/', isCorrect: false },
      { text: '/aɪ/', isCorrect: false },
      { text: '/eə/', isCorrect: true },
      { text: '/ʊə/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '“/ এই /” ধ্বনিটির আইপিএ (IPA) কী?',
    answers: [
      { text: '/eɪ/', isCorrect: true },
      { text: '/aɪ/', isCorrect: false },
      { text: '/eə/', isCorrect: false },
      { text: '/ʊə/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '"History" শব্দটির IPA কী?',
    answers: [
      { text: '/ˈhos tri/', isCorrect: false },
      { text: '/ˈhɪs tori/', isCorrect: false },
      { text: '/ˈhɪs tri/', isCorrect: true },
      { text: '/ˈhɪs turi/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '"Food" শব্দটির IPA কী?',
    answers: [
      { text: '/f oː d/', isCorrect: false },
      { text: '/f aː d/', isCorrect: false },
      { text: '/f iː d/', isCorrect: false },
      { text: '/f uː d/', isCorrect: true },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '"Nature" শব্দটির IPA কী?',
    answers: [
      { text: '/ˈne tʃə(r)/', isCorrect: false },
      { text: '/ˈneɪ tʃə(r)/', isCorrect: true },
      { text: '/ˈneɪ tu(r)/', isCorrect: false },
      { text: '/ˈneɪ tu(r)e/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '"Cup" শব্দটির IPA কী?',
    answers: [
      { text: '/k a: p/', isCorrect: false },
      { text: '/k u p/', isCorrect: false },
      { text: '/k u: p/', isCorrect: false },
      { text: '/k ʌ p/', isCorrect: true },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '"Doctor" শব্দটির IPA কী?',
    answers: [
      { text: '/ˈdɒk tə(r)/', isCorrect: true },
      { text: '/ˈdək tə(r)/', isCorrect: false },
      { text: '/ˈdʌk tə(r)/', isCorrect: false },
      { text: '/ˈdɒk tɒ(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '"Book" শব্দটির IPA কী?',
    answers: [
      { text: '/b u: k/', isCorrect: false },
      { text: '/b ʊ k/', isCorrect: true },
      { text: '/b o k/', isCorrect: false },
      { text: '/b ɒ k/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: '"Father" শব্দটির IPA কী?',
    answers: [
      { text: '/ˈfɑː ðə(r)/', isCorrect: true },
      { text: '/ˈfʌ ðə(r)/', isCorrect: false },
      { text: '/ˈfə ðə(r)/', isCorrect: false },
      { text: '/ˈfɑː θə(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'এই IPA “/ɑː s k/”-এর ইংরেজি শব্দটি কী?',
    answers: [
      { text: 'Ask', isCorrect: true },
      { text: 'Go', isCorrect: false },
      { text: 'Think', isCorrect: false },
      { text: 'Add', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'এই IPA “/ˈpiː pl/”-এর ইংরেজি শব্দটি কী?',
    answers: [
      { text: 'Peiple', isCorrect: false },
      { text: 'Piple', isCorrect: false },
      { text: 'People', isCorrect: true },
      { text: 'Payple', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'এই IPA “/æ d/”-এর জন্য ইংরেজি শব্দটি কী?',
    answers: [
      { text: 'Add', isCorrect: true },
      { text: 'Bad', isCorrect: false },
      { text: 'Mad', isCorrect: false },
      { text: 'Cat', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'IPA-এর পূর্ণ রূপ কী?',
    answers: [
      { text: 'International Phonetic Association', isCorrect: false },
      { text: 'International Phonetic Alphabet', isCorrect: true },
      { text: 'Indian Phonetic Alphabet', isCorrect: false },
      { text: 'Internal Phonetic Alphabet', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'IPA তে Short Vowel Sound কয়টি?',
    answers: [
      { text: '5', isCorrect: false },
      { text: '6', isCorrect: false },
      { text: '7', isCorrect: true },
      { text: '8', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'IPA তে Long Vowel Sound কয়টি?',
    answers: [
      { text: '5', isCorrect: true },
      { text: '6', isCorrect: false },
      { text: '7', isCorrect: false },
      { text: '8', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'IPA-তে Diphthongs কয়টি??',
    answers: [
      { text: '6', isCorrect: false },
      { text: '7', isCorrect: false },
      { text: '8', isCorrect: true },
      { text: '9', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'IPA-তে Vowel Sounds কয়টি?',
    answers: [
      { text: '12', isCorrect: false },
      { text: '20', isCorrect: true },
      { text: '24', isCorrect: false },
      { text: '44', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'IPA-তে Consonant Sounds কয়টি?',
    answers: [
      { text: '12', isCorrect: false },
      { text: '20', isCorrect: false },
      { text: '24', isCorrect: true },
      { text: '44', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'IPA-তে মোট Symbol বা Sounds কয়টি?',
    answers: [
      { text: '20', isCorrect: false },
      { text: '24', isCorrect: false },
      { text: '44', isCorrect: true },
      { text: '50', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'ইংরেজি শিখতে IPA কেন কাজে লাগে?',
    answers: [
      { text: 'ব্যাকরণগত নির্ভুলতা উন্নত করতে', isCorrect: false },
      { text: 'ভোকাবুলারি বা শব্দভাণ্ডার বাড়াতে', isCorrect: false },
      { text: 'সঠিক উচ্চারণ শিখতে', isCorrect: true },
      { text: 'বাক্য অনুবাদ করতে', isCorrect: false },
    ],
  },
];
