import type { Question } from './types';

export const newEnglishLevel6Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Age' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/eɪdʒ/', isCorrect: true },
      { text: '/æd/', isCorrect: false },
      { text: '/eər/', isCorrect: false },
      { text: '/ɔːl/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/æz/ এটি কোন শব্দের সঠিক উচ্চারণ?",
    answers: [
      { text: 'As', isCorrect: true },
      { text: 'Ask', isCorrect: false },
      { text: 'At', isCorrect: false },
      { text: 'Art', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Ask' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ɑːsk/', isCorrect: true },
      { text: '/æt/', isCorrect: false },
      { text: '/ɑːrm/', isCorrect: false },
      { text: '/eɪdʒ/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/bæk/ এটি নিচের কোন শব্দটির উচ্চারণ?",
    answers: [
      { text: 'Back', isCorrect: true },
      { text: 'Bag', isCorrect: false },
      { text: 'Bad', isCorrect: false },
      { text: 'Ball', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Bath' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/bɑːθ/', isCorrect: true },
      { text: '/bi/', isCorrect: false },
      { text: '/bɔːl/', isCorrect: false },
      { text: '/bed/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/eni/ এটি কোন শব্দের সঠিক IPA রূপ?",
    answers: [
      { text: 'Any', isCorrect: true },
      { text: 'And', isCorrect: false },
      { text: 'All', isCorrect: false },
      { text: 'Air', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Art' শব্দটির সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/ɑːrt/', isCorrect: true },
      { text: '/ɑːrm/', isCorrect: false },
      { text: '/æt/', isCorrect: false },
      { text: '/æd/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/bæɡ/ এটি কোন শব্দটির উচ্চারণ?",
    answers: [
      { text: 'Bag', isCorrect: true },
      { text: 'Big', isCorrect: false },
      { text: 'Back', isCorrect: false },
      { text: 'Boy', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Body' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/ˈbɒdi/', isCorrect: true },
      { text: '/bed/', isCorrect: false },
      { text: '/bɔɪ/', isCorrect: false },
      { text: '/bi/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/æd/ এটি কোন শব্দের IPA সংকেত?",
    answers: [
      { text: 'Add', isCorrect: true },
      { text: 'Age', isCorrect: false },
      { text: 'Air', isCorrect: false },
      { text: 'Any', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Ball' শব্দের সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/bɔːl/', isCorrect: true },
      { text: '/bɑːθ/', isCorrect: false },
      { text: '/bi/', isCorrect: false },
      { text: '/bed/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/eər/ এটি কোন শব্দের সঠিক IPA রূপ?",
    answers: [
      { text: 'Air', isCorrect: true },
      { text: 'Arm', isCorrect: false },
      { text: 'Art', isCorrect: false },
      { text: 'As', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Bed' শব্দটির সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/bed/', isCorrect: true },
      { text: '/bæd/', isCorrect: false },
      { text: '/bi/', isCorrect: false },
      { text: '/bɔɪ/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/bi/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Be', isCorrect: true },
      { text: 'Bed', isCorrect: false },
      { text: 'By', isCorrect: false },
      { text: 'Big', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Big' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/bɪɡ/', isCorrect: true },
      { text: '/bed/', isCorrect: false },
      { text: '/bi/', isCorrect: false },
      { text: '/bæk/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/bɔɪ/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Boy', isCorrect: true },
      { text: 'Bag', isCorrect: false },
      { text: 'Ball', isCorrect: false },
      { text: 'Bad', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Book' শব্দটির সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/bʊk/', isCorrect: true },
      { text: '/bɔɪ/', isCorrect: false },
      { text: '/bed/', isCorrect: false },
      { text: '/bæk/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/kæt/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Cat', isCorrect: true },
      { text: 'Cut', isCorrect: false },
      { text: 'Car', isCorrect: false },
      { text: 'Cup', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Cut' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/kʌt/', isCorrect: true },
      { text: '/kæt/', isCorrect: false },
      { text: '/kɑː(r)/', isCorrect: false },
      { text: '/kəʊt/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/æt/ এটি কোন শব্দের IPA রূপ?",
    answers: [
      { text: 'At', isCorrect: true },
      { text: 'As', isCorrect: false },
      { text: 'Art', isCorrect: false },
      { text: 'Add', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Ability' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/əˈbɪləti/', isCorrect: true },
      { text: '/ˈeɪbl/', isCorrect: false },
      { text: '/əˈbrɔːd/', isCorrect: false },
      { text: '/əkˈsept/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/əˈbrɔːd/ এটি কোন শব্দের সঠিক উচ্চারণ?",
    answers: [
      { text: 'Abroad', isCorrect: true },
      { text: 'Ability', isCorrect: false },
      { text: 'Achieve', isCorrect: false },
      { text: 'Acid', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Accept' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/əkˈsept/', isCorrect: true },
      { text: '/ˈæksɪdənt/', isCorrect: false },
      { text: '/ˈæsɪd/', isCorrect: false },
      { text: '/ˈeɪbl/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/'æksɪdənt/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Accident', isCorrect: true },
      { text: 'Accuracy', isCorrect: false },
      { text: 'Achieve', isCorrect: false },
      { text: 'Acid', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Achievement' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/əˈtʃiːvmənt/', isCorrect: true },
      { text: '/əˈtʃiːv/', isCorrect: false },
      { text: '/ˈæktɪveɪt/', isCorrect: false },
      { text: '/ˈæktɪv/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/əˈkɔːrdɪŋli/ এটি কোন শব্দের IPA রূপ?",
    answers: [
      { text: 'Accordingly', isCorrect: true },
      { text: 'According to', isCorrect: false },
      { text: 'Accuracy', isCorrect: false },
      { text: 'Accurately', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Accuracy' শব্দটির সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/ˈækjərəsi/', isCorrect: true },
      { text: '/əˈtʃiːv/', isCorrect: false },
      { text: '/ˈeɪkə(r)/', isCorrect: false },
      { text: '/əkˈsept/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/əˈtʃiːv/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Achieve', isCorrect: true },
      { text: 'Acid', isCorrect: false },
      { text: 'Acre', isCorrect: false },
      { text: 'Act', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Acid' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/ˈæsɪd/', isCorrect: true },
      { text: '/ˈæksɪdənt/', isCorrect: false },
      { text: '/ˈæktɪv/', isCorrect: false },
      { text: '/əˈfekt/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/ˈeɪkə(r)/ এটি কোন শব্দের সঠিক উচ্চারণ?",
    answers: [
      { text: 'Acre', isCorrect: true },
      { text: 'Acid', isCorrect: false },
      { text: 'Act', isCorrect: false },
      { text: 'Able', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Activate' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/ˈæktɪveɪt/', isCorrect: true },
      { text: '/ˌæktɪˈveɪʃn/', isCorrect: false },
      { text: '/ˈæktɪv/', isCorrect: false },
      { text: '/ˈæktɪvɪst/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/ˈæktɪv/ এটি কোন শব্দের সঠিক উচ্চারণ?",
    answers: [
      { text: 'Active', isCorrect: true },
      { text: 'Act', isCorrect: false },
      { text: 'Acid', isCorrect: false },
      { text: 'Actor', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Activist' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/ˈæktɪvɪst/', isCorrect: true },
      { text: '/ækˈtɪvəti/', isCorrect: false },
      { text: '/ˈæktʃuəl/', isCorrect: false },
      { text: '/ˈæktɪv/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/ækˈtɪvəti/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Activity', isCorrect: true },
      { text: 'Active', isCorrect: false },
      { text: 'Actual', isCorrect: false },
      { text: 'Action', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Actual' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/ˈæktʃuəl/', isCorrect: true },
      { text: '/əkˈsept/', isCorrect: false },
      { text: '/əˈfekt/', isCorrect: false },
      { text: '/ədˈvɑːntɪdʒ/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/ədˈvɑːntɪdʒ/ এটি কোন শব্দের IPA রূপ?",
    answers: [
      { text: 'Advantage', isCorrect: true },
      { text: 'Adventure', isCorrect: false },
      { text: 'Advertise', isCorrect: false },
      { text: 'Afternoon', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Adventure' শব্দটির সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/ədˈventʃə(r)/', isCorrect: true },
      { text: '/ədˈvɑːntɪdʒ/', isCorrect: false },
      { text: '/ˌædvəˈtaɪzmənt/', isCorrect: false },
      { text: '/əˈlaʊ/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/əˈfekt/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Affect', isCorrect: true },
      { text: 'Affection', isCorrect: false },
      { text: 'Afraid', isCorrect: false },
      { text: 'After', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Afraid' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/əˈfreɪd/', isCorrect: true },
      { text: '/əˈfekt/', isCorrect: false },
      { text: '/əˈpɪə(r)/', isCorrect: false },
      { text: '/əˈlaʊ/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/ɔːlˈðəʊ/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Although', isCorrect: true },
      { text: 'Alone', isCorrect: false },
      { text: 'Already', isCorrect: false },
      { text: 'Always', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Abdomen' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/ˈæbdəmən/', isCorrect: true },
      { text: '/ˈɑːrmpɪt/', isCorrect: false },
      { text: '/ˈɑːrtəri/', isCorrect: false },
      { text: '/blʌd/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/ˈɑːrmpɪt/ এটি শরীরের কোন অঙ্গের উচ্চারণ?",
    answers: [
      { text: 'Armpit', isCorrect: true },
      { text: 'Artery', isCorrect: false },
      { text: 'Abdomen', isCorrect: false },
      { text: 'Arm', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Artery' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ˈɑːrtəri/', isCorrect: true },
      { text: '/ˈɑːrmpɪt/', isCorrect: false },
      { text: '/ˈæbdəmən/', isCorrect: false },
      { text: '/blʌd/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/ˈbækbəʊn/ এটি কোন শব্দের IPA রূপ?",
    answers: [
      { text: 'Backbone', isCorrect: true },
      { text: 'Back', isCorrect: false },
      { text: 'Body', isCorrect: false },
      { text: 'Bone', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Beard' শব্দটির সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/bɪəd/', isCorrect: true },
      { text: '/ˈbeli/', isCorrect: false },
      { text: '/blʌd/', isCorrect: false },
      { text: '/bəʊn/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/ˈbeli/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Belly', isCorrect: true },
      { text: 'Body', isCorrect: false },
      { text: 'Blood', isCorrect: false },
      { text: 'Beard', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Blood' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/blʌd/', isCorrect: true },
      { text: '/ˈbeli/', isCorrect: false },
      { text: '/bəʊn/', isCorrect: false },
      { text: '/bɪəd/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/bəʊn/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Bone', isCorrect: true },
      { text: 'Body', isCorrect: false },
      { text: 'Blood', isCorrect: false },
      { text: 'Backbone', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Cheek' শব্দটির সঠিক উচ্চারণ কোনটি?",
    answers: [
      { text: '/tʃiːk/', isCorrect: true },
      { text: '/tʃest/', isCorrect: false },
      { text: '/tʃɪn/', isCorrect: false },
      { text: '/tʃɔː/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/tʃest/ এটি শরীরের কোন অঙ্গের সঠিক IPA?",
    answers: [
      { text: 'Chest', isCorrect: true },
      { text: 'Cheek', isCorrect: false },
      { text: 'Chin', isCorrect: false },
      { text: 'Chor', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Chin' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/tʃɪn/', isCorrect: true },
      { text: '/tʃiːk/', isCorrect: false },
      { text: '/tʃest/', isCorrect: false },
      { text: '/tʃɔː/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/ˈelbəʊ/ এটি কোন শব্দের সঠিক উচ্চারণ?",
    answers: [
      { text: 'Elbow', isCorrect: true },
      { text: 'Eye', isCorrect: false },
      { text: 'Ear', isCorrect: false },
      { text: 'Eyelid', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Eyelid' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/ˈaɪlɪd/', isCorrect: true },
      { text: '/aɪ/', isCorrect: false },
      { text: '/ˈelbəʊ/', isCorrect: false },
      { text: '/ɪə(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/feɪs/ এটি কোন শব্দের সঠিক IPA রূপ?",
    answers: [
      { text: 'Face', isCorrect: true },
      { text: 'Finger', isCorrect: false },
      { text: 'Foot', isCorrect: false },
      { text: 'Forehead', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Finger' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/ˈfɪŋɡə(r)/', isCorrect: true },
      { text: '/fʊt/', isCorrect: false },
      { text: '/feɪs/', isCorrect: false },
      { text: '/fɪst/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/fʊt/ এটি কোন শব্দের উচ্চারণ?",
    answers: [
      { text: 'Foot', isCorrect: true },
      { text: 'Face', isCorrect: false },
      { text: 'Finger', isCorrect: false },
      { text: 'Forehead', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Hair' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/heə(r)/', isCorrect: true },
      { text: '/hænd/', isCorrect: false },
      { text: '/hed/', isCorrect: false },
      { text: '/hɑːrt/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/niː/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত?",
    answers: [
      { text: 'Knee', isCorrect: true },
      { text: 'Key', isCorrect: false },
      { text: 'Know', isCorrect: false },
      { text: 'Neck', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "'Shoulder' শব্দটির সঠিক IPA কোনটি?",
    answers: [
      { text: '/ˈʃəʊldə(r)/', isCorrect: true },
      { text: '/ˈstʌmək/', isCorrect: false },
      { text: '/ˈskɪn/', isCorrect: false },
      { text: '/skʌl/', isCorrect: false },
    ],
  },
  {
    level: '0.6',
    subject: 'English',
    questionText: "/ˈtʌŋ/ এটি কোন শব্দের সঠিক IPA রূপ?",
    answers: [
      { text: 'Tongue', isCorrect: true },
      { text: 'Teeth', isCorrect: false },
      { text: 'Toe', isCorrect: false },
      { text: 'Throat', isCorrect: false },
    ],
  },
];
