
import type { Question } from './types';

export const newEnglishLevel9Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Abridge' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'বাড়িয়ে বলা', isCorrect: false },
      { text: 'সংক্ষেপ করা', isCorrect: true },
      { text: 'ধ্বংস করা', isCorrect: false },
      { text: 'গ্রহণ করা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Agile' শব্দটির সঠিক অর্থ কী?",
    answers: [
      { text: 'অলস', isCorrect: false },
      { text: 'সাবলীল ও চটপটে', isCorrect: true },
      { text: 'খুব লম্বা', isCorrect: false },
      { text: 'স্থির', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Altitude' শব্দটির সঠিক বাংলা প্রতিশব্দ কোনটি?",
    answers: [
      { text: 'গভীরতা', isCorrect: false },
      { text: 'উচ্চতা', isCorrect: true },
      { text: 'প্রশস্থতা', isCorrect: false },
      { text: 'ওজন', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Anthropology' বলতে কী বোঝায়?",
    answers: [
      { text: 'নৃবিজ্ঞান', isCorrect: true },
      { text: 'প্রাণিবিজ্ঞান', isCorrect: false },
      { text: 'জ্যোতির্বিজ্ঞান', isCorrect: false },
      { text: 'ভূতত্ত্ব', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Apace' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'ধীর গতিতে', isCorrect: false },
      { text: 'দ্রুত গতিতে', isCorrect: true },
      { text: 'মাঝেমধ্যে', isCorrect: false },
      { text: 'কখনোই নয়', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Apathy' শব্দটির সঠিক বাংলা অর্থ কী?",
    answers: [
      { text: 'গভীর মনোযোগ', isCorrect: false },
      { text: 'প্রবল উৎসাহ', isCorrect: false },
      { text: 'উদাসীনতা বা অনাগ্রহ', isCorrect: true },
      { text: 'সহানুভূতি', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Aptitude' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'স্বাভাবিক দক্ষতা বা প্রবণতা', isCorrect: true },
      { text: 'উচ্চতা', isCorrect: false },
      { text: 'ঘ্রাণশক্তি', isCorrect: false },
      { text: 'শ্রবনশক্তি', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Arctic' শব্দটির বাংলা অর্থ কী?",
    answers: [
      { text: 'মরুভূমি অঞ্চল', isCorrect: false },
      { text: 'উত্তর মেরু বা সুমেরু অঞ্চল', isCorrect: true },
      { text: 'গ্রীষ্মমন্ডল', isCorrect: false },
      { text: 'পাহাড়ী অঞ্চল', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Assay' শব্দটির অর্থ কী?",
    answers: [
      { text: 'প্রবন্ধ লেখা', isCorrect: false },
      { text: 'বিশুদ্ধতা পরীক্ষা করা', isCorrect: true },
      { text: 'সাহায্য করা', isCorrect: false },
      { text: 'আক্রমণ করা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Assorted' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'একই রকমের', isCorrect: false },
      { text: 'বিভিন্ন রকমের', isCorrect: true },
      { text: 'পচে যাওয়া', isCorrect: false },
      { text: 'নতুন', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/əˈbrɪdʒ/ এটি কোন শব্দের সঠিক উচ্চারণ (IPA)?",
    answers: [
      { text: 'Abridge', isCorrect: true },
      { text: 'Average', isCorrect: false },
      { text: 'Advantage', isCorrect: false },
      { text: 'Arrange', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ədˈmɪʃn/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Admission', isCorrect: true },
      { text: 'Addition', isCorrect: false },
      { text: 'Action', isCorrect: false },
      { text: 'Ambition', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈædʒaɪl/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Angel', isCorrect: false },
      { text: 'Agile', isCorrect: true },
      { text: 'Again', isCorrect: false },
      { text: 'Agent', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈæltɪtjuːd/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Attitude', isCorrect: false },
      { text: 'Altitude', isCorrect: true },
      { text: 'Aptitude', isCorrect: false },
      { text: 'Amplitude', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈæŋɡlɪŋ/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Angling', isCorrect: true },
      { text: 'Angry', isCorrect: false },
      { text: 'Angle', isCorrect: false },
      { text: 'Ankle', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈænɪmɪzəm/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Animal', isCorrect: false },
      { text: 'Animism', isCorrect: true },
      { text: 'Animation', isCorrect: false },
      { text: 'Anoint', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/əˈpeɪs/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Space', isCorrect: false },
      { text: 'Apace', isCorrect: true },
      { text: 'Apple', isCorrect: false },
      { text: 'Apply', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈæpəθi/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Apathy', isCorrect: true },
      { text: 'Ability', isCorrect: false },
      { text: 'Apply', isCorrect: false },
      { text: 'Anyway', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/ˈæptɪtjuːd/ এটি কোন শব্দের সঠিক IPA?",
    answers: [
      { text: 'Attitude', isCorrect: false },
      { text: 'Altitude', isCorrect: false },
      { text: 'Aptitude', isCorrect: true },
      { text: 'Arctic', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "/əˈseɪ/ এটি কোন শব্দের উচ্চারণ সংকেত?",
    answers: [
      { text: 'Essay', isCorrect: false },
      { text: 'Assay', isCorrect: true },
      { text: 'Away', isCorrect: false },
      { text: 'Always', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Witch' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/wɪtʃ/', isCorrect: true },
      { text: '/wɒtʃ/', isCorrect: false },
      { text: '/wɪʃ/', isCorrect: false },
      { text: '/wɪθ/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Withhold' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/wɪðˈhəʊld/', isCorrect: true },
      { text: '/wɪθˈaʊt/', isCorrect: false },
      { text: '/wɪðˈɪn/', isCorrect: false },
      { text: '/wɪðˈdrɔː/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Womb' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/wuːm/', isCorrect: true },
      { text: '/wɒm/', isCorrect: false },
      { text: '/wʌm/', isCorrect: false },
      { text: '/wuːnd/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Yelp' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/jelp/', isCorrect: true },
      { text: '/jelpɪŋ/', isCorrect: false },
      { text: '/help/', isCorrect: false },
      { text: '/self/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Willful' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwɪlfl/', isCorrect: true },
      { text: '/ˈwɪlɪŋ/', isCorrect: false },
      { text: '/ˈwaɪli/', isCorrect: false },
      { text: '/wɪl/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Willy-nilly' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˌwɪli ˈnɪli/', isCorrect: true },
      { text: '/ˈwɪli/', isCorrect: false },
      { text: '/ˈnɪli/', isCorrect: false },
      { text: '/ˌwɪli ˈwɪli/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Wily' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwaɪli/', isCorrect: true },
      { text: '/ˈwɪli/', isCorrect: false },
      { text: '/ˈwaɪf/', isCorrect: false },
      { text: '/ˈwɪndɪ/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Winnow' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwɪnəʊ/', isCorrect: true },
      { text: '/ˈwɪndəʊ/', isCorrect: false },
      { text: '/ˈwɪnə(r)/', isCorrect: false },
      { text: '/ˈwɪnɪŋ/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Winsome' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwɪnsəm/', isCorrect: true },
      { text: '/ˈwɪntə(r)/', isCorrect: false },
      { text: '/wɪn/', isCorrect: false },
      { text: '/ˈwelkəm/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Anoint' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/əˈnɔɪnt/', isCorrect: true },
      { text: '/əˈnaʊns/', isCorrect: false },
      { text: '/ˈænədʌɪz/', isCorrect: false },
      { text: '/ˈæntiruːm/', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Rainy day' - এর সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'বৃষ্টির দিন', isCorrect: false },
      { text: 'সুদিন', isCorrect: false },
      { text: 'দুর্দিন', isCorrect: true },
      { text: 'ছুটির দিন', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"অনুরূপ হওয়া" - এর সঠিক ইংরেজি ইডিয়ম কোনটি?',
    answers: [
      { text: 'Take place', isCorrect: false },
      { text: 'Take after', isCorrect: true },
      { text: 'Take off', isCorrect: false },
      { text: 'Take up', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'End in smoke' - ইডিয়মটির অর্থ কী?",
    answers: [
      { text: 'আগুন লাগা', isCorrect: false },
      { text: 'ধোঁয়া হওয়া', isCorrect: false },
      { text: 'সফল হওয়া', isCorrect: false },
      { text: 'নিষ্ফল হওয়া', isCorrect: true },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"মুখস্থ করা" - এর সঠিক ইংরেজি ফ্রেজ কোনটি?',
    answers: [
      { text: 'Commit to memory', isCorrect: true },
      { text: 'Come round', isCorrect: false },
      { text: 'Catch sight of', isCorrect: false },
      { text: 'Cut off', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'The lion's share' - এর সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'সিংহের গর্জন', isCorrect: false },
      { text: 'প্রধান অংশ বা সিংহভাগ', isCorrect: true },
      { text: 'ছোট অংশ', isCorrect: false },
      { text: 'বনের রাজা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"চোখে ধুলা দেওয়া" - এর সঠিক ইংরেজি কোনটি?',
    answers: [
      { text: "Throw dust in one's eyes", isCorrect: true },
      { text: 'See through', isCorrect: false },
      { text: 'Look after', isCorrect: false },
      { text: 'Skim through', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Dead against' - বলতে কী বোঝায়?",
    answers: [
      { text: 'মৃত ব্যক্তি', isCorrect: false },
      { text: 'ঘোরবিরোধী', isCorrect: true },
      { text: 'খুব কাছে', isCorrect: false },
      { text: 'সমমনা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"তাল মিলিয়ে চলা" - এর সঠিক ইংরেজি ইডিয়ম কোনটি?',
    answers: [
      { text: 'Cope with', isCorrect: true },
      { text: 'Cut out', isCorrect: false },
      { text: 'Come round', isCorrect: false },
      { text: 'Catch up', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Far and wide' - এর সঠিক বাংলা অর্থ কী?",
    answers: [
      { text: 'সর্বত্র', isCorrect: true },
      { text: 'অনেক দূরে', isCorrect: false },
      { text: 'প্রশস্ত রাস্তা', isCorrect: false },
      { text: 'সংকীর্ণ', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"আরোগ্য লাভ করা" - এর সঠিক ইংরেজি কোনটি?',
    answers: [
      { text: 'Come round', isCorrect: true },
      { text: 'Come across', isCorrect: false },
      { text: 'Come by', isCorrect: false },
      { text: 'Come in', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Storm in a tea cup' - ইডিয়মটির অর্থ কী?",
    answers: [
      { text: 'ঝোড়ো হাওয়া', isCorrect: false },
      { text: 'তুচ্ছ বিষয়ে তুমুল কাণ্ড', isCorrect: true },
      { text: 'চা পান করা', isCorrect: false },
      { text: 'আনন্দ করা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"তাৎক্ষণিকভাবে" - এর ইংরেজি ইডিয়ম কোনটি?',
    answers: [
      { text: 'Then and there', isCorrect: true },
      { text: 'To and fro', isCorrect: false },
      { text: 'Far and near', isCorrect: false },
      { text: 'Out and out', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Skim through' - এর সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'গভীরভাবে পড়া', isCorrect: false },
      { text: 'হালকাভাবে পাঠ করা', isCorrect: true },
      { text: 'সাঁতার কাটা', isCorrect: false },
      { text: 'রান্না করা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"ঘটা" - এর সঠিক ইংরেজি ইডিয়ম কোনটি?',
    answers: [
      { text: 'Take place', isCorrect: true },
      { text: 'Take part', isCorrect: false },
      { text: 'Take away', isCorrect: false },
      { text: 'Take in', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'To and fro' - এর অর্থ কী?",
    answers: [
      { text: 'এদিক-ওদিক', isCorrect: true },
      { text: 'উপরে-নিচে', isCorrect: false },
      { text: 'আগে-পিছে', isCorrect: false },
      { text: 'সত্য-মিথ্যা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"অপ্রচলিত ভাষা" - এর সঠিক ইংরেজি কোনটি?',
    answers: [
      { text: 'Dead language', isCorrect: true },
      { text: 'Old language', isCorrect: false },
      { text: 'New language', isCorrect: false },
      { text: 'Mother tongue', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Catch sight of' - বলতে কী বোঝায়?",
    answers: [
      { text: 'দেখা পাওয়া', isCorrect: true },
      { text: 'অন্ধ হওয়া', isCorrect: false },
      { text: 'দৃষ্টিশক্তি হারানো', isCorrect: false },
      { text: 'ভুলে যাওয়া', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"হাল ছেড়ে দেওয়া/ত্যাগ করা" - এর ইংরেজি ইডিয়ম কোনটি?',
    answers: [
      { text: 'Give up', isCorrect: true },
      { text: 'Give in', isCorrect: false },
      { text: 'Give away', isCorrect: false },
      { text: 'Give out', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Every nook and corner' - এর সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'মাঝখানে', isCorrect: false },
      { text: 'সর্বত্র / কোণায় কোণায়', isCorrect: true },
      { text: 'বাইরের দিকে', isCorrect: false },
      { text: 'বাগানের ভেতরে', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"বাদ দেওয়া" - এর সঠিক ইংরেজি ইডিয়ম কোনটি?',
    answers: [
      { text: 'Cut off', isCorrect: false },
      { text: 'Cut out', isCorrect: true },
      { text: 'Cut down', isCorrect: false },
      { text: 'Cut in', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Cold war' - এর সঠিক বাংলা অর্থ কী?",
    answers: [
      { text: 'ঠান্ডা লড়াই', isCorrect: true },
      { text: 'শীতকাল', isCorrect: false },
      { text: 'বরফ যুদ্ধ', isCorrect: false },
      { text: 'শান্ত পরিবেশ', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"সহ্য করা" - এর সঠিক ইংরেজি ইডিয়ম কোনটি?',
    answers: [
      { text: 'Put up with', isCorrect: true },
      { text: 'Put down', isCorrect: false },
      { text: 'Put off', isCorrect: false },
      { text: 'Put out', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Drop out' - ইডিয়মটির অর্থ কী?",
    answers: [
      { text: 'ঝরে পড়া বা বিরত থাকা', isCorrect: true },
      { text: 'ভর্তি হওয়া', isCorrect: false },
      { text: 'উপরে ওঠা', isCorrect: false },
      { text: 'খেলা করা', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"টুকে রাখা বা লিখে রাখা" - এর ইংরেজি ইডিয়ম কোনটি?',
    answers: [
      { text: 'Put down', isCorrect: true },
      { text: 'Put on', isCorrect: false },
      { text: 'Set up', isCorrect: false },
      { text: 'Call on', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Through thick and thin' - এর সঠিক বাংলা অর্থ কী?",
    answers: [
      { text: 'মোটা ও চিকন', isCorrect: false },
      { text: 'বিপদে-আপদে সব অবস্থায়', isCorrect: true },
      { text: 'গভীর জঙ্গলে', isCorrect: false },
      { text: 'খুব সহজে', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"নিশ্চিতভাবে" - এর সঠিক ইংরেজি কোনটি?',
    answers: [
      { text: 'For certain', isCorrect: true },
      { text: 'For now', isCorrect: false },
      { text: 'For ever', isCorrect: false },
      { text: 'For good', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'In the long run' - এর অর্থ কী?",
    answers: [
      { text: 'লম্বা দৌড়', isCorrect: false },
      { text: 'শেষ পর্যন্ত / পরিণামে', isCorrect: true },
      { text: 'অনেক আগে', isCorrect: false },
      { text: 'অনেক পরে', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"যাতে" - এর সঠিক ইংরেজি লিঙ্কার বা ফ্রেজ কোনটি?',
    answers: [
      { text: 'So that', isCorrect: true },
      { text: 'In order to', isCorrect: false },
      { text: 'As if', isCorrect: false },
      { text: 'Even though', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: "'Out of order' - এর সঠিক বাংলা অর্থ কী?",
    answers: [
      { text: 'সুশৃঙ্খল', isCorrect: false },
      { text: 'বিকল বা অকেজো', isCorrect: true },
      { text: 'আদেশের বাইরে', isCorrect: false },
      { text: 'নতুন', isCorrect: false },
    ],
  },
  {
    level: '0.9',
    subject: 'English',
    questionText: '"বিচ্ছিন্ন করা" - এর সঠিক ইংরেজি ইডিয়ম কোনটি?',
    answers: [
      { text: 'Cut off', isCorrect: true },
      { text: 'Cut in', isCorrect: false },
      { text: 'Cut out', isCorrect: false },
      { text: 'Cut up', isCorrect: false },
    ],
  },
];
