import type { Question } from './types';

export const newBengaliLevel0Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মানুষের সত্তাকে লেখক কয়টি তলার সাথে তুলনা করেছেন?',
    answers: [
      { text: 'একটি', isCorrect: false },
      { text: 'দুটি', isCorrect: true },
      { text: 'তিনটি', isCorrect: false },
      { text: 'চারটি', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মানুষের জীবসত্তার ঘরটিকে লেখক কীসের সাথে তুলনা করেছেন?',
    answers: [
      { text: 'ওপর তলা', isCorrect: false },
      { text: 'নিচতলা', isCorrect: true },
      { text: 'মাঝতলা', isCorrect: false },
      { text: 'পাশের ঘর', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'জীবসত্তার ঘর থেকে মনুষ্যত্বের ঘরে ওঠার মই কোনটি?',
    answers: [
      { text: 'সম্পদ', isCorrect: false },
      { text: 'জ্ঞান', isCorrect: false },
      { text: 'শিক্ষা', isCorrect: true },
      { text: 'পরিশ্রম', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষার আসল কাজ কোনটি?',
    answers: [
      { text: 'জ্ঞান দান করা', isCorrect: false },
      { text: 'জীবিকা নির্বাহ করা', isCorrect: false },
      { text: 'মূল্যবোধ সৃষ্টি করা', isCorrect: true },
      { text: 'সমাজসেবা করা', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: '‘শিক্ষা ও মনুষ্যত্ব’ প্রবন্ধে মানুষের কয়টি সত্তার কথা উল্লেখ আছে?',
    answers: [
      { text: 'দুই', isCorrect: true },
      { text: 'তিন', isCorrect: false },
      { text: 'চার', isCorrect: false },
      { text: 'পাঁচ', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষার অপ্রয়োজনীয় দিক কোনটি?',
    answers: [
      { text: 'মূল্যবোধ সৃষ্টি', isCorrect: false },
      { text: 'মনুষ্যত্ব অর্জন', isCorrect: false },
      { text: 'জীবিকা অর্জন', isCorrect: true },
      { text: 'স্বাধীনতা রক্ষা', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'কোন দিকটিকে লেখক শিক্ষার ‘শ্রেষ্ঠ দিক’ বলেছেন?',
    answers: [
      { text: 'প্রয়োজনীয় দিক', isCorrect: false },
      { text: 'অপ্রয়োজনীয় দিক', isCorrect: true },
      { text: 'তাত্ত্বিক দিক', isCorrect: false },
      { text: 'ব্যবহারিক দিক', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষার অপ্রয়োজনীয় দিকটি আমাদের কী শেখায়?',
    answers: [
      { text: 'টাকা উপার্জন করা', isCorrect: false },
      { text: 'জীবনকে উপভোগ করা', isCorrect: true },
      { text: 'হিসাব করা', isCorrect: false },
      { text: 'চাকরি করা', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মানুষের মুক্তির জন্য লেখক কয়টি উপায়ের কথা বলেছেন?',
    answers: [
      { text: 'একটি', isCorrect: false },
      { text: 'দুটি', isCorrect: true },
      { text: 'তিনটি', isCorrect: false },
      { text: 'চারটি', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: '‘অন্নবস্ত্রের প্রাচুর্যের চেয়েও মুক্তি বড়’—এখানে মুক্তি বলতে কী বোঝানো হয়েছে?',
    answers: [
      { text: 'কারামুক্তি', isCorrect: false },
      { text: 'অন্নচিন্তা থেকে মুক্তি', isCorrect: false },
      { text: 'আত্মিক মুক্তি বা মনুষ্যত্ব', isCorrect: true },
      { text: 'পরাধীনতা থেকে মুক্তি', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'আমাদের দেশের অধিকাংশ মানুষ কিসের নিগড়ে বা শিকলে বন্দি?',
    answers: [
      { text: 'অভাবের', isCorrect: false },
      { text: 'অশিক্ষার', isCorrect: false },
      { text: 'অর্থচিন্তার', isCorrect: true },
      { text: 'অন্ধবিশ্বাসের', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'কারা বন্দিশালার অন্ধকারই সবচেয়ে বেশি উপভোগ করে?',
    answers: [
      { text: 'যারা বাইরে বের হতে ভয় পায়', isCorrect: false },
      { text: 'যারা ক্ষুধার্ত', isCorrect: false },
      { text: 'যারা মুক্তির স্বাদ কখনো পায়নি', isCorrect: true },
      { text: 'যারা অলস', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: '‘লেফাফাদুরস্তি’ শব্দের অর্থ কী?',
    answers: [
      { text: 'ভেতরের গুণ', isCorrect: false },
      { text: 'বাইরের চাকচিক্য', isCorrect: true },
      { text: 'পরিপাটি পোশাক', isCorrect: false },
      { text: 'শিষ্টাচার', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: '‘ক্ষুৎপিপাসা’ শব্দের অর্থ কী?',
    answers: [
      { text: 'ক্ষুধা ও তৃষ্ণা', isCorrect: true },
      { text: 'দুঃখ ও কষ্ট', isCorrect: false },
      { text: 'রোগ ও শোক', isCorrect: false },
      { text: 'অন্ন ও বস্ত্র', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'লোভে পাপ, পাপে মৃত্যু—এই কথাটি কোন জগতের ক্ষেত্রে বেশি সত্য?',
    answers: [
      { text: 'বস্তুজগতের', isCorrect: false },
      { text: 'আধ্যাত্মিক বা আত্মিক জগতের', isCorrect: true },
      { text: 'পরকালের', isCorrect: false },
      { text: 'কাল্পনিক জগতের', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষার কাজ মানুষকে কিসের স্বাদ দেওয়া?',
    answers: [
      { text: 'ধন-সম্পদের', isCorrect: false },
      { text: 'মনুষ্যত্বের', isCorrect: true },
      { text: 'আভিজাত্যের', isCorrect: false },
      { text: 'ক্ষমতার', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: '‘পিঞ্জরাবদ্ধ পাখি’ বলতে লেখক কাদের বুঝিয়েছেন?',
    answers: [
      { text: 'খাঁচার পাখি', isCorrect: false },
      { text: 'পরাধীন মানুষ', isCorrect: false },
      { text: 'কেবল আহার-বিহার প্রত্যাশী মানুষ', isCorrect: true },
      { text: 'কারাবন্দি', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মানুষের অস্তিত্ব রক্ষার জন্য কোনটি আগে প্রয়োজন?',
    answers: [
      { text: 'জীবসত্তা রক্ষা', isCorrect: true },
      { text: 'মনুষ্যত্ব লাভ', isCorrect: false },
      { text: 'উচ্চশিক্ষা', isCorrect: false },
      { text: 'আভিজাত্য', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মনুষ্যত্বলোকের ঘরটি কোথায় অবস্থিত?',
    answers: [
      { text: 'নিচতলায়', isCorrect: false },
      { text: 'ওপরতলায়', isCorrect: true },
      { text: 'বাইরে', isCorrect: false },
      { text: 'মাঝতলায়', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'জীবনের আসল সার্থকতা কিসে?',
    answers: [
      { text: 'প্রচুর অর্থ উপার্জনে', isCorrect: false },
      { text: 'মনুষ্যত্ব অর্জনে', isCorrect: true },
      { text: 'ভালো পোশাক পরায়', isCorrect: false },
      { text: 'ক্ষমতাবান হওয়াতে', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: '‘খুঁটে খাওয়া’ বলতে লেখক কী বুঝিয়েছেন?',
    answers: [
      { text: 'পাখির মতো খাওয়া', isCorrect: false },
      { text: 'সামান্য উপার্জনে কেবল টিকে থাকা', isCorrect: true },
      { text: 'পরিশ্রম করা', isCorrect: false },
      { text: 'অন্যের ওপর নির্ভর করা', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'কার চিন্তা থেকে মুক্তি না পেলে মানুষের মনুষ্যত্ব জাগে না?',
    answers: [
      { text: 'সামাজিক মর্যাদার', isCorrect: false },
      { text: 'পরকালের', isCorrect: false },
      { text: 'অন্নবস্ত্রের', isCorrect: true },
      { text: 'শিক্ষার', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মুক্তির জন্য অন্নবস্ত্রের সমাধানের সাথে আর কী প্রয়োজন?',
    answers: [
      { text: 'রাজনৈতিক ক্ষমতা', isCorrect: false },
      { text: 'সঠিক শিক্ষা', isCorrect: true },
      { text: 'প্রচুর সম্পদ', isCorrect: false },
      { text: 'বিদেশ ভ্রমণ', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: '‘বিত্ত’ অপেক্ষা কী বড়?',
    answers: [
      { text: 'চিত্ত', isCorrect: true },
      { text: 'নাম', isCorrect: false },
      { text: 'ক্ষমতা', isCorrect: false },
      { text: 'রূপ', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'কোনটি মানুষকে প্রকৃত বড় করতে পারে না?',
    answers: [
      { text: 'শিক্ষা', isCorrect: false },
      { text: 'বাইরের জৌলুস বা চাকচিক্য', isCorrect: true },
      { text: 'মনুষ্যত্ব', isCorrect: false },
      { text: 'উদারতা', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'অন্নবস্ত্রের সমস্যার সমাধান কেন প্রয়োজন?',
    answers: [
      { text: 'বিলাসিতার জন্য', isCorrect: false },
      { text: 'মানুষ হওয়ার সুযোগ পাওয়ার জন্য', isCorrect: true },
      { text: 'অলস হওয়ার জন্য', isCorrect: false },
      { text: 'ধনী হওয়ার জন্য', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মনুষ্যত্বের আহ্বানে মানুষ কী অনুভব করে?',
    answers: [
      { text: 'ভয়', isCorrect: false },
      { text: 'পরাধীনতা', isCorrect: false },
      { text: 'স্বাধীনতা ও মহত্ত্ব', isCorrect: true },
      { text: 'একাকীত্ব', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'জীবসত্তার ঘর থেকে মনুষ্যত্বের ঘরে যাওয়ার উপায় কী?',
    answers: [
      { text: 'অর্থ উপার্জন', isCorrect: false },
      { text: 'রাজনীতি করা', isCorrect: false },
      { text: 'শিক্ষা গ্রহণ', isCorrect: true },
      { text: 'দেশ ভ্রমণ', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'প্রকৃত শিক্ষার ফলে মানুষের কিসের বিকাশ ঘটে?',
    answers: [
      { text: 'লালসার', isCorrect: false },
      { text: 'সহমর্মিতা ও উদারতার', isCorrect: true },
      { text: 'দম্ভের', isCorrect: false },
      { text: 'আলস্যের', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'লোভের ফলে মানুষের কীসের মৃত্যু ঘটে?',
    answers: [
      { text: 'দেহের', isCorrect: false },
      { text: 'আত্মার', isCorrect: true },
      { text: 'বুদ্ধির', isCorrect: false },
      { text: 'শক্তির', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: '‘শিক্ষা ও মনুষ্যত্ব’ প্রবন্ধে অন্নবস্ত্রের সমস্যাকে কিসের সাথে তুলনা করা হয়েছে?',
    answers: [
      { text: 'শিকল', isCorrect: true },
      { text: 'অন্ধকার', isCorrect: false },
      { text: 'দেয়াল', isCorrect: false },
      { text: 'কারা প্রাচীর', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষা মানুষকে কোন জগতের খবর দেয়?',
    answers: [
      { text: 'জীবসত্তার', isCorrect: false },
      { text: 'মনুষ্যত্ব লোকের', isCorrect: true },
      { text: 'পাতালপুরের', isCorrect: false },
      { text: 'নক্ষত্রলোকের', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মানুষের আত্মা কখন ছোট হয়ে যায়?',
    answers: [
      { text: 'পড়াশোনা না করলে', isCorrect: false },
      { text: 'অন্নবস্ত্রের চিন্তায় ব্যস্ত থাকলে', isCorrect: true },
      { text: 'কাজ না করলে', isCorrect: false },
      { text: 'গরিব হলে', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষার মাধ্যমে কোনটি অর্জিত হয়?',
    answers: [
      { text: 'গাড়ি-বাড়ি', isCorrect: false },
      { text: 'মানবতা বা মনুষ্যত্ব', isCorrect: true },
      { text: 'উচ্চপদ', isCorrect: false },
      { text: 'সমাজসেবা', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষার আসল রূপ কোনটি?',
    answers: [
      { text: 'পরীক্ষায় পাস করা', isCorrect: false },
      { text: 'বড় চাকরি পাওয়া', isCorrect: false },
      { text: 'অন্তরের মুক্তি', isCorrect: true },
      { text: 'বই মুখস্থ করা', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: '‘নিগড়’ শব্দের অর্থ কী?',
    answers: [
      { text: 'শিকল বা বেড়ি', isCorrect: true },
      { text: 'অন্ধকার', isCorrect: false },
      { text: 'আলো', isCorrect: false },
      { text: 'দেয়াল', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষার ফল কী হওয়া উচিত?',
    answers: [
      { text: 'অনেক অর্থ', isCorrect: false },
      { text: 'মানুষের মুক্তি', isCorrect: true },
      { text: 'রাজনৈতিক জয়', isCorrect: false },
      { text: 'উচ্চ বংশমর্যাদা', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'মানুষ যখন অন্নচিন্তার নিগড়ে বন্দি থাকে, তখন সে কী অনুভব করে না?',
    answers: [
      { text: 'ক্ষুধা', isCorrect: false },
      { text: 'তৃষ্ণা', isCorrect: false },
      { text: 'মুক্তির আনন্দ', isCorrect: true },
      { text: 'ক্লান্তি', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'জীবসত্তার প্রয়োজনে কোনটি অপরিহার্য?',
    answers: [
      { text: 'অন্নবস্ত্র', isCorrect: true },
      { text: 'কবিতা', isCorrect: false },
      { text: 'দর্শন', isCorrect: false },
      { text: 'সংগীত', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'Bengali',
    questionText: 'শিক্ষার অপ্রয়োজনীয় দিকটি কেন শ্রেষ্ঠ?',
    answers: [
      { text: 'কারণ এটি টাকা দেয়', isCorrect: false },
      { text: 'কারণ এটি মানুষকে বড় হতে সাহায্য করে', isCorrect: false },
      { text: 'কারণ এটি মানুষকে মনুষ্যত্বের স্বাদ দেয়', isCorrect: true },
      { text: 'কারণ এটি সহজ', isCorrect: false },
    ],
  },
];
