import type { Question } from './types';

export const newEnglishLevel0Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the Bengali equivalent sound of “/e/ ”?',
    answers: [
      { text: '/ ই /', isCorrect: false },
      { text: '/ এ /', isCorrect: true },
      { text: '/ অ্যা/ ', isCorrect: false },
      { text: '/ আ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the Bengali equivalent sound of “/ɒ/ ”?',
    answers: [
      { text: '/ এ /', isCorrect: false },
      { text: '/ অ্যা/ ', isCorrect: false },
      { text: '/ আ /', isCorrect: false },
      { text: '/ অ /', isCorrect: true },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the Bengali equivalent sound of “/æ/ ”?',
    answers: [
      { text: '/ অ্যা/ ', isCorrect: true },
      { text: '/ আ /', isCorrect: false },
      { text: '/ অ /', isCorrect: false },
      { text: '/ উ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the Bengali equivalent sound of “/ɜː/ ”?',
    answers: [
      { text: '/ ঈ /', isCorrect: false },
      { text: '/ আ /', isCorrect: true },
      { text: '/ উ /', isCorrect: false },
      { text: '/ অ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the Bengali equivalent sound of “/ɔː/ ”?',
    answers: [
      { text: '/ আ /', isCorrect: false },
      { text: '/ অ /', isCorrect: true },
      { text: '/ উ /', isCorrect: false },
      { text: '/ ঈ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the Bengali equivalent sound of “/eɪ/”?',
    answers: [
      { text: '/ আই /', isCorrect: false },
      { text: '/ অই /', isCorrect: false },
      { text: '/ ইআ /', isCorrect: false },
      { text: '/ এই /', isCorrect: true },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the Bengali equivalent sound of “/ɔɪ/ ”?',
    answers: [
      { text: '/ এই /', isCorrect: false },
      { text: '/ আই /', isCorrect: false },
      { text: '/ অই /', isCorrect: true },
      { text: '/ ইআ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the Bengali equivalent sound of “/ʊə/ ”?',
    answers: [
      { text: '/ এআ /', isCorrect: false },
      { text: '/ উআ /', isCorrect: true },
      { text: '/ ওাউ /', isCorrect: false },
      { text: '/ আউ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the Bengali equivalent sound of “/ʤ/ ”?',
    answers: [
      { text: '/ জ্ /', isCorrect: true },
      { text: '/ থ্ /', isCorrect: false },
      { text: '/ দ্ /', isCorrect: false },
      { text: '/ শ্ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the Bengali equivalent sound of “/ð/ ”?',
    answers: [
      { text: '/ জ্ /', isCorrect: false },
      { text: '/ থ্ /', isCorrect: false },
      { text: '/ দ্ /', isCorrect: true },
      { text: '/ শ্ /', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA of this sound “/ ইং / ”?',
    answers: [
      { text: '/ʧ/', isCorrect: false },
      { text: '/j/', isCorrect: false },
      { text: '/ŋ/', isCorrect: true },
      { text: '/ʃ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA of this sound “/ চ্ /”?',
    answers: [
      { text: '/ʧ/', isCorrect: true },
      { text: '/j/', isCorrect: false },
      { text: '/ŋ/', isCorrect: false },
      { text: '/ʃ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA of this sound “/ ইয়া /”?',
    answers: [
      { text: '/ʧ/', isCorrect: false },
      { text: '/j/', isCorrect: true },
      { text: '/ŋ/', isCorrect: false },
      { text: '/ʃ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA of this sound “/ ঈ / ”?',
    answers: [
      { text: '/iː/', isCorrect: true },
      { text: '/ɑː/', isCorrect: false },
      { text: '/ɔː/', isCorrect: false },
      { text: '/uː/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA of this sound “/ ই /”?',
    answers: [
      { text: '/e/', isCorrect: false },
      { text: '/æ/', isCorrect: false },
      { text: '/I/', isCorrect: true },
      { text: '/ʌ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA of this sound “/ ওয়া /”?',
    answers: [
      { text: '/ʊə/', isCorrect: false },
      { text: '/əʊ/', isCorrect: false },
      { text: '/aʊ/', isCorrect: false },
      { text: '/w/', isCorrect: true },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA of this sound “/ স্ /”?',
    answers: [
      { text: '/s/', isCorrect: true },
      { text: '/z/', isCorrect: false },
      { text: '/ʃ/', isCorrect: false },
      { text: '/ʤ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: "What is the IPA for the 'sh' sound?",
    answers: [
      { text: '/s/', isCorrect: false },
      { text: '/z/', isCorrect: false },
      { text: '/ʃ/', isCorrect: true },
      { text: '/ʤ/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA of this sound “/ এআ /”?',
    answers: [
      { text: '/eɪ/', isCorrect: false },
      { text: '/aɪ/', isCorrect: false },
      { text: '/eə/', isCorrect: true },
      { text: '/ʊə/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA of this sound “/ এই /”?',
    answers: [
      { text: '/eɪ/', isCorrect: true },
      { text: '/aɪ/', isCorrect: false },
      { text: '/eə/', isCorrect: false },
      { text: '/ʊə/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA for the word “History”?',
    answers: [
      { text: '/ˈhos tri/', isCorrect: false },
      { text: '/ˈhɪs tori/', isCorrect: false },
      { text: '/ˈhɪs tri/', isCorrect: true },
      { text: '/ˈhɪs turi/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA for the word “Food”?',
    answers: [
      { text: '/f oː d/', isCorrect: false },
      { text: '/f aː d/', isCorrect: false },
      { text: '/f iː d/', isCorrect: false },
      { text: '/f uː d/', isCorrect: true },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA for the word “Nature”?',
    answers: [
      { text: '/ˈne tʃə(r)/', isCorrect: false },
      { text: '/ˈneɪ tʃə(r)/', isCorrect: true },
      { text: '/ˈneɪ tu(r)/', isCorrect: false },
      { text: '/ˈneɪ tu(r)e/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA for the word “Cup”?',
    answers: [
      { text: '/k a: p/', isCorrect: false },
      { text: '/k u p/', isCorrect: false },
      { text: '/k u: p/', isCorrect: false },
      { text: '/k ʌ p/', isCorrect: true },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA for the word “Doctor”?',
    answers: [
      { text: '/ˈdɒk tə(r)/', isCorrect: true },
      { text: '/ˈdək tə(r)/', isCorrect: false },
      { text: '/ˈdʌk tə(r)/', isCorrect: false },
      { text: '/ˈdɒk tɒ(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA for the word “Book”?',
    answers: [
      { text: '/b u: k/', isCorrect: false },
      { text: '/b ʊ k/', isCorrect: true },
      { text: '/b o k/', isCorrect: false },
      { text: '/b ɒ k/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the IPA for the word “Father”?',
    answers: [
      { text: '/ˈfɑː ðə(r)/', isCorrect: true },
      { text: '/ˈfʌ ðə(r)/', isCorrect: false },
      { text: '/ˈfə ðə(r)/', isCorrect: false },
      { text: '/ˈfɑː θə(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the English word for this IPA “/ɑː s k/”?',
    answers: [
      { text: 'Ask', isCorrect: true },
      { text: 'Go', isCorrect: false },
      { text: 'Think', isCorrect: false },
      { text: 'Add', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the English word for this IPA “/ˈpiː pl/”?',
    answers: [
      { text: 'Peiple', isCorrect: false },
      { text: 'Piple', isCorrect: false },
      { text: 'People', isCorrect: true },
      { text: 'Payple', isCorrect: false },
    ],
  },
  {
    level: '0.0',
    subject: 'English',
    questionText: 'What is the English word for this IPA “/æ d/ ”?',
    answers: [
      { text: 'Add', isCorrect: true },
      { text: 'Bad', isCorrect: false },
      { text: 'Mad', isCorrect: false },
      { text: 'Cat', isCorrect: false },
    ],
  },
];
