import type { Question } from './types';

export const newEnglishLevel1Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Always' বলতে কী বোঝায়?",
    answers: [
      { text: 'কখনও না', isCorrect: false },
      { text: 'মাঝে মাঝে', isCorrect: false },
      { text: 'সবসময়', isCorrect: true },
      { text: 'প্রতিদিন', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Between' শব্দটির অর্থ কী?",
    answers: [
      { text: 'ভেতরে', isCorrect: false },
      { text: 'বাইরে', isCorrect: false },
      { text: 'দুইয়ের মধ্যে', isCorrect: true },
      { text: 'উপরে', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Daughter' এর বাংলা অর্থ কী?",
    answers: [
      { text: 'পুত্র', isCorrect: false },
      { text: 'বোন', isCorrect: false },
      { text: 'কন্যা', isCorrect: true },
      { text: 'মা', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Early' শব্দটির অর্থ কী?",
    answers: [
      { text: 'দেরিতে', isCorrect: false },
      { text: 'তাড়াতাড়ি বা ভোরে', isCorrect: true },
      { text: 'রাত্রে', isCorrect: false },
      { text: 'দুপুরে', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Every' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'কিছু', isCorrect: false },
      { text: 'প্রতিটি', isCorrect: true },
      { text: 'অনেক', isCorrect: false },
      { text: 'কোনটিই নয়', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Famous' বলতে কী বোঝায়?",
    answers: [
      { text: 'ধনী', isCorrect: false },
      { text: 'বিখ্যাত', isCorrect: true },
      { text: 'গরিব', isCorrect: false },
      { text: 'পরিচিত', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Friend' এর সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'শত্রু', isCorrect: false },
      { text: 'বন্ধু', isCorrect: true },
      { text: 'ভাই', isCorrect: false },
      { text: 'শিক্ষক', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Garden' শব্দটির অর্থ কী?",
    answers: [
      { text: 'মাঠ', isCorrect: false },
      { text: 'পুকুর', isCorrect: false },
      { text: 'বাগান', isCorrect: true },
      { text: 'জঙ্গল', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Great' বলতে কী বোঝায়?",
    answers: [
      { text: 'ছোট', isCorrect: false },
      { text: 'সাধারণ', isCorrect: false },
      { text: 'মহান বা বড়', isCorrect: true },
      { text: 'খারাপ', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Health' শব্দটির অর্থ কী?",
    answers: [
      { text: 'সম্পদ', isCorrect: false },
      { text: 'স্বাস্থ্য', isCorrect: true },
      { text: 'অসুখ', isCorrect: false },
      { text: 'শক্তি', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'History' এর সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'ভূগোল', isCorrect: false },
      { text: 'বিজ্ঞান', isCorrect: false },
      { text: 'ইতিহাস', isCorrect: true },
      { text: 'গণিত', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Important' শব্দটির অর্থ কী?",
    answers: [
      { text: 'সাধারণ', isCorrect: false },
      { text: 'অপ্রয়োজনীয়', isCorrect: false },
      { text: 'গুরুত্বপূর্ণ', isCorrect: true },
      { text: 'জরুরি', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Kitchen' বলতে কী বোঝায়?",
    answers: [
      { text: 'শোবার ঘর', isCorrect: false },
      { text: 'পড়ার ঘর', isCorrect: false },
      { text: 'রান্নাঘর', isCorrect: true },
      { text: 'বসার ঘর', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Learn' শব্দটির অর্থ কী?",
    answers: [
      { text: 'শেখা', isCorrect: true },
      { text: 'শোনা', isCorrect: false },
      { text: 'পড়া', isCorrect: false },
      { text: 'লেখা', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Listen' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'দেখা', isCorrect: false },
      { text: 'শোনা', isCorrect: true },
      { text: 'বলা', isCorrect: false },
      { text: 'হাসা', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Message' এর বাংলা অর্থ কী?",
    answers: [
      { text: 'সংবাদ বা বার্তা', isCorrect: true },
      { text: 'চিঠি', isCorrect: false },
      { text: 'কথা', isCorrect: false },
      { text: 'গল্প', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Mountain' শব্দটির অর্থ কী?",
    answers: [
      { text: 'নদী', isCorrect: false },
      { text: 'সাগর', isCorrect: false },
      { text: 'পাহাড়/পর্বত', isCorrect: true },
      { text: 'বন', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Neighbor' বলতে কী বোঝায়?",
    answers: [
      { text: 'আত্মীয়', isCorrect: false },
      { text: 'প্রতিবেশী', isCorrect: true },
      { text: 'বন্ধু', isCorrect: false },
      { text: 'অপরিচিত', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Often' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'মাঝে মাঝে', isCorrect: false },
      { text: 'সর্বদা', isCorrect: false },
      { text: 'প্রায়ই', isCorrect: true },
      { text: 'কখনও না', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'People' এর বাংলা অর্থ কী?",
    answers: [
      { text: 'সমাজ', isCorrect: false },
      { text: 'জনগণ/মানুষ', isCorrect: true },
      { text: 'পরিবার', isCorrect: false },
      { text: 'ছাত্র', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Question' শব্দটির অর্থ কী?",
    answers: [
      { text: 'উত্তর', isCorrect: false },
      { text: 'প্রশ্ন', isCorrect: true },
      { text: 'সমাধান', isCorrect: false },
      { text: 'বাক্য', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Ready' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'প্রস্তুত', isCorrect: true },
      { text: 'অলস', isCorrect: false },
      { text: 'ব্যস্ত', isCorrect: false },
      { text: 'শেষ', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Remember' বলতে কী বোঝায়?",
    answers: [
      { text: 'ভুলে যাওয়া', isCorrect: false },
      { text: 'মনে রাখা', isCorrect: true },
      { text: 'দেখা', isCorrect: false },
      { text: 'শোনা', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Sentence' এর বাংলা অর্থ কী?",
    answers: [
      { text: 'শব্দ', isCorrect: false },
      { text: 'অক্ষর', isCorrect: false },
      { text: 'বাক্য', isCorrect: true },
      { text: 'প্যারাগ্রাফ', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Simple' শব্দটির অর্থ কী?",
    answers: [
      { text: 'কঠিন', isCorrect: false },
      { text: 'জটিল', isCorrect: false },
      { text: 'সহজ/সরল', isCorrect: true },
      { text: 'বাঁকা', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Spell' শব্দটির অর্থ কী?",
    answers: [
      { text: 'পড়া', isCorrect: false },
      { text: 'বানান করা', isCorrect: true },
      { text: 'আঁকা', isCorrect: false },
      { text: 'দৌড়ানো', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Story' এর সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'ইতিহাস', isCorrect: false },
      { text: 'কবিতা', isCorrect: false },
      { text: 'গল্প', isCorrect: true },
      { text: 'গান', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Talk' শব্দটির অর্থ কী?",
    answers: [
      { text: 'কথা বলা', isCorrect: true },
      { text: 'চুপ থাকা', isCorrect: false },
      { text: 'হাঁটা', isCorrect: false },
      { text: 'ঘুমানো', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Teach' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'ছাত্র', isCorrect: false },
      { text: 'শিক্ষা দেওয়া', isCorrect: true },
      { text: 'পরীক্ষা দেওয়া', isCorrect: false },
      { text: 'শেখা', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Together' বলতে কী বোঝায়?",
    answers: [
      { text: 'আলাদা', isCorrect: false },
      { text: 'একাকী', isCorrect: false },
      { text: 'একত্রে', isCorrect: true },
      { text: 'দূরে', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: "'Understand' শব্দটির অর্থ কী?",
    answers: [
      { text: 'বোঝা', isCorrect: true },
      { text: 'ভুলে যাওয়া', isCorrect: false },
      { text: 'চিন্তা করা', isCorrect: false },
      { text: 'ঘুমানো', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: 'Cat /kæt/ শব্দটিতে ব্যবহৃত /æ/ ধ্বনিটির বাংলা উচ্চারণ কী হবে?',
    answers: [
      { text: 'আ', isCorrect: false },
      { text: 'এ', isCorrect: false },
      { text: 'অ্যা', isCorrect: true },
      { text: 'অ', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: '/ʌ/ এই IPA সংকেতটি কোন শব্দের উচ্চারণে ব্যবহৃত হয়?',
    answers: [
      { text: 'Put', isCorrect: false },
      { text: 'Cut', isCorrect: true },
      { text: 'Pot', isCorrect: false },
      { text: 'Pet', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: 'Bird /bɜːd/ শব্দটির /ɜː/ ধ্বনিটির উচ্চারণ কেমন?',
    answers: [
      { text: 'অতি ক্ষুদ্র ‘অ’', isCorrect: false },
      { text: 'দীর্ঘ ‘আ.......’', isCorrect: true },
      { text: 'দীর্ঘ ‘ই.......’', isCorrect: false },
      { text: '‘অ্যা’', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: '/ɔɪ/ এই Diphthong-টি নিচের কোন শব্দে পাওয়া যায়?',
    answers: [
      { text: 'Boy', isCorrect: true },
      { text: 'Buy', isCorrect: false },
      { text: 'Bay', isCorrect: false },
      { text: 'Bow', isCorrect: false },
    ],
  },
  {
    level: '0.1',
    subject: 'English',
    questionText: '‘Half’ /hɑːf/ শব্দটিতে কোন ধরনের ‘আ’ ধ্বনি আছে?',
    answers: [
      { text: 'হ্রস্ব আ', isCorrect: false },
      { text: 'দীর্ঘ আ......', isCorrect: true },
      { text: 'অ্যা', isCorrect: false },
      { text: 'ও', isCorrect: false },
    ],
  },
];
