import type { Question } from './types';

export const newEnglishLevel3Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Vacation' শব্দটির সঠিক বাংলা অর্থ কোনটি?",
    answers: [
      { text: 'কাজ', isCorrect: false },
      { text: 'ছুটি', isCorrect: true },
      { text: 'ভ্রমণ', isCorrect: false },
      { text: 'উৎসব', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Vegetable' বলতে কী বোঝায়?",
    answers: [
      { text: 'ফলমূল', isCorrect: false },
      { text: 'আমিষ', isCorrect: false },
      { text: 'শাক-সবজি', isCorrect: true },
      { text: 'মশলা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Village' শব্দটির সঠিক IPA উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ˈvɪlɪdʒ/', isCorrect: true },
      { text: '/ˈvɪdɪəʊ/', isCorrect: false },
      { text: '/ˈvɪzɪt/', isCorrect: false },
      { text: '/ˈwɔːtə(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Visitor' বলতে কাকে বোঝানো হয়?",
    answers: [
      { text: 'পরিদর্শক বা দর্শনার্থী', isCorrect: true },
      { text: 'দোকানদার', isCorrect: false },
      { text: 'ছাত্র', isCorrect: false },
      { text: 'কৃষক', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Watch' (verb) শব্দটির অর্থ কী?",
    answers: [
      { text: 'ঘড়ি', isCorrect: false },
      { text: 'দেখা', isCorrect: true },
      { text: 'শোনা', isCorrect: false },
      { text: 'বলা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Weather' শব্দটির বাংলা অর্থ কী?",
    answers: [
      { text: 'জল', isCorrect: false },
      { text: 'আকাশ', isCorrect: false },
      { text: 'আবহাওয়া', isCorrect: true },
      { text: 'বাতাস', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Weekend' বলতে সপ্তাহের কোন সময়কে বোঝায়?",
    answers: [
      { text: 'সপ্তাহের শুরু', isCorrect: false },
      { text: 'সপ্তাহের মাঝখানে', isCorrect: false },
      { text: 'সাপ্তাহিক ছুটি', isCorrect: true },
      { text: 'প্রতিদিন', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Weekly' শব্দটির অর্থ কী?",
    answers: [
      { text: 'মাসিক', isCorrect: false },
      { text: 'বার্ষিক', isCorrect: false },
      { text: 'দৈনিক', isCorrect: false },
      { text: 'সাপ্তাহিক', isCorrect: true },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Welcome' (verb) বলতে কী বোঝায়?",
    answers: [
      { text: 'বিদায় জানানো', isCorrect: false },
      { text: 'সম্ভাষণ জানানো', isCorrect: true },
      { text: 'ঘৃণা করা', isCorrect: false },
      { text: 'ডাকা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Welfare' বা 'Well-being' শব্দ দুটির অর্থ কী?",
    answers: [
      { text: 'বিপদ', isCorrect: false },
      { text: 'সম্পদ', isCorrect: false },
      { text: 'কল্যাণ বা মঙ্গল', isCorrect: true },
      { text: 'স্বাস্থ্য', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Western' বলতে কোন দিককে বোঝানো হয়?",
    answers: [
      { text: 'উত্তর', isCorrect: false },
      { text: 'দক্ষিণ', isCorrect: false },
      { text: 'পূর্ব', isCorrect: false },
      { text: 'পশ্চিম', isCorrect: true },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Whatever' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'যাই হোক', isCorrect: true },
      { text: 'কখনো না', isCorrect: false },
      { text: 'সবখানে', isCorrect: false },
      { text: 'কেন', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Water' শব্দটির সঠিক IPA উচ্চারণ কোনটি?",
    answers: [
      { text: '/ˈwɔːtə(r)/', isCorrect: true },
      { text: '/weə(r)/', isCorrect: false },
      { text: '/wɒtʃ/', isCorrect: false },
      { text: '/ˈvɪzɪt/', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Wear' শব্দটির অর্থ কী?",
    answers: [
      { text: 'কেনা', isCorrect: false },
      { text: 'পরিধান করা', isCorrect: true },
      { text: 'ধোয়া', isCorrect: false },
      { text: 'ছিঁড়ে ফেলা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Website' বলতে কী বোঝায়?",
    answers: [
      { text: 'খবরের কাগজ', isCorrect: false },
      { text: 'ওয়েবসাইট', isCorrect: true },
      { text: 'বই', isCorrect: false },
      { text: 'চিঠি', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "/ˌwiːk ˈend/ এটি কোন শব্দের IPA রূপ?",
    answers: [
      { text: 'Weekly', isCorrect: false },
      { text: 'Weekend', isCorrect: true },
      { text: 'Welcome', isCorrect: false },
      { text: 'Welfare', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Washing' শব্দটির সঠিক অর্থ কোনটি?",
    answers: [
      { text: 'রান্নাকরা', isCorrect: false },
      { text: 'ধৌতকরণ কাজ', isCorrect: true },
      { text: 'পরিষ্কার করা', isCorrect: false },
      { text: 'খেলাধুলা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Villager' বলতে কী বোঝায়?",
    answers: [
      { text: 'শহরবাসী', isCorrect: false },
      { text: 'দেশবাসী', isCorrect: false },
      { text: 'গ্রামবাসী', isCorrect: true },
      { text: 'প্রতিবেশী', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Visit' (verb) শব্দটির অর্থ কী?",
    answers: [
      { text: 'পরিদর্শন করা', isCorrect: true },
      { text: 'বাস করা', isCorrect: false },
      { text: 'বাগান করা', isCorrect: false },
      { text: 'কেনাকাটা করা', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Video' শব্দটির সঠিক IPA সংকেত কোনটি?",
    answers: [
      { text: '/ˈvɪdɪəʊ/', isCorrect: true },
      { text: '/ˈvɪlɪdʒ/', isCorrect: false },
      { text: '/ˈwetni/', isCorrect: false },
      { text: '/ˈwelkəm/', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Vacation' শব্দটির সঠিক IPA উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/veɪˈkeɪʃn/', isCorrect: true },
      { text: '/ˈwedʒtəbl/', isCorrect: false },
      { text: '/ˈvɪzɪt/', isCorrect: false },
      { text: '/ˈwɔːtə(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Vegetable' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈvɪdɪəʊ/', isCorrect: false },
      { text: '/ˈwedʒtəbl/', isCorrect: true },
      { text: '/ˈvɪlɪdʒ/', isCorrect: false },
      { text: '/ˈweðə(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "/ˈvɪlɪdʒ/ এটি কোন শব্দের সঠিক উচ্চারণ সংকেত?",
    answers: [
      { text: 'Visit', isCorrect: false },
      { text: 'Video', isCorrect: false },
      { text: 'Village', isCorrect: true },
      { text: 'Vacation', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Visitor' শব্দটির সঠিক IPA সংকেত কোনটি?",
    answers: [
      { text: '/ˈvɪzɪtə(r)/', isCorrect: true },
      { text: '/ˈvɪlɪdʒə(r)/', isCorrect: false },
      { text: '/wɒtʃ/', isCorrect: false },
      { text: '/ˈwestərn/', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Water' শব্দটিতে ব্যবহৃত /ɔː/ ধ্বনিটি কোন ধরনের স্বরধ্বনি?",
    answers: [
      { text: 'Short Vowel', isCorrect: false },
      { text: 'Long Vowel', isCorrect: true },
      { text: 'Diphthong', isCorrect: false },
      { text: 'Consonant', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Weather' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈweðə(r)/', isCorrect: true },
      { text: '/weə(r)/', isCorrect: false },
      { text: '/ˈvɪzɪt/', isCorrect: false },
      { text: '/wɒtʃ/', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "/ˌwiːk ˈend/ এটি কোন শব্দের সঠিক IPA রূপ?",
    answers: [
      { text: 'Weekly', isCorrect: false },
      { text: 'Welcome', isCorrect: false },
      { text: 'Weekend', isCorrect: true },
      { text: 'Welfare', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Weekly' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/ˈwiːkli/', isCorrect: true },
      { text: '/ˈwelkəm/', isCorrect: false },
      { text: '/ˈwebsaɪt/', isCorrect: false },
      { text: '/wɒtˈevə(r)/', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Welcome' শব্দটির সঠিক IPA রূপ কোনটি?",
    answers: [
      { text: '/ˈwelkəm/', isCorrect: true },
      { text: '/ˈwelfiː/', isCorrect: false },
      { text: '/ˈwelbiːɪŋ/', isCorrect: false },
      { text: '/ˈwestərn/', isCorrect: false },
    ],
  },
  {
    level: '0.3',
    subject: 'English',
    questionText: "'Whatever' শব্দটির সঠিক উচ্চারণ সংকেত কোনটি?",
    answers: [
      { text: '/wɒtˈevə(r)/', isCorrect: true },
      { text: '/ˈwɒʃɪŋ/', isCorrect: false },
      { text: '/weə(r)/', isCorrect: false },
      { text: '/ˈvɪdɪəʊ/', isCorrect: false },
    ],
  },
];
