import type { Question } from './types';

export const newBengaliLevel4Questions: Omit<Question, 'id'>[] = [
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'রবীন্দ্রনাথ ঠাকুরের কত বছর বয়সে এই প্রবন্ধটি লেখা?',
    answers: [
      { text: 'সত্তর', isCorrect: false },
      { text: 'আশি', isCorrect: true },
      { text: 'নব্বই', isCorrect: false },
      { text: 'পঁচাত্তর', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'লেখকের জীবনক্ষেত্রে কোন জাতির ইতিহাসের সঙ্গে প্রথম পরিচয় ঘটেছিল?',
    answers: [
      { text: 'ফরাসি', isCorrect: false },
      { text: 'জাপানি', isCorrect: false },
      { text: 'ইংরেজ', isCorrect: true },
      { text: 'জার্মান', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'ইংরেজ জাতির কোন গুণটি দেখে লেখক তাদের হৃদয়ের উচ্চাসনে বসিয়েছিলেন?',
    answers: [
      { text: 'চাতুর্য', isCorrect: false },
      { text: 'ব্যবসায়িক বুদ্ধি', isCorrect: false },
      { text: 'ঔদার্য ও মানবমৈত্রী', isCorrect: true },
      { text: 'কঠোর শাসন', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: "'সিভিলিজেশন' শব্দের পরিবর্তে মনু কোন শব্দটি ব্যবহার করেছেন?",
    answers: [
      { text: 'সংস্কৃতি', isCorrect: false },
      { text: 'সদাচার', isCorrect: true },
      { text: 'সভ্যতা', isCorrect: false },
      { text: 'লোকাচার', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: "'সদাচার' প্রাচীনকালে কোন ভৌগোলিক সীমায় বদ্ধ ছিল?",
    answers: [
      { text: 'আর্যাবর্ত', isCorrect: false },
      { text: 'ব্রহ্মাবর্ত', isCorrect: true },
      { text: 'দাক্ষিণাত্য', isCorrect: false },
      { text: 'বঙ্গদেশ', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'ব্রহ্মাবর্তের সদাচার কোন দুটি নদীর মধ্যবর্তী স্থানে প্রচলিত ছিল?',
    answers: [
      { text: 'গঙ্গা ও যমুনা', isCorrect: false },
      { text: 'সরস্বতী ও দৃশদ্বতী', isCorrect: true },
      { text: 'সিন্ধু ও ঝিলাম', isCorrect: false },
      { text: 'নর্মদা ও তাপ্তী', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'ইংরেজি শিক্ষার প্রভাবে লেখক কোন বিষয়ের বিরুদ্ধে বিদ্রোহ দেখেছিলেন?',
    answers: [
      { text: 'রাজশাসন', isCorrect: false },
      { text: 'বাহ্যিক আচার-সর্বস্বতা', isCorrect: true },
      { text: 'নতুন শিক্ষা', isCorrect: false },
      { text: 'বিজ্ঞান', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'লেখক কার বর্ণিত শিক্ষিত সম্প্রদায়ের বিবরণের কথা উল্লেখ করেছেন?',
    answers: [
      { text: 'রামমোহন রায়', isCorrect: false },
      { text: 'রাজনারায়ণ বসু', isCorrect: true },
      { text: 'বিদ্যাসাগর', isCorrect: false },
      { text: 'বঙ্কিমচন্দ্র', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'লেখক পার্লামেন্টে কার বক্তৃতা শুনেছিলেন?',
    answers: [
      { text: 'মেকলে', isCorrect: false },
      { text: 'বার্ক', isCorrect: false },
      { text: 'জন ব্রাইট', isCorrect: true },
      { text: 'শেক্সপিয়র', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'লেখক ভারতবর্ষের জনসাধারণের মধ্যে কী দেখে ব্যথিত হয়েছিলেন?',
    answers: [
      { text: 'অশিক্ষা', isCorrect: false },
      { text: 'নিদারুণ দারিদ্র্য', isCorrect: true },
      { text: 'কুসংস্কার', isCorrect: false },
      { text: 'বিদ্রোহ', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'কোন দেশ যন্ত্রচালনার সাহায্যে দ্রুত সম্পদশালী হয়ে উঠেছিল?',
    answers: [
      { text: 'চীন', isCorrect: false },
      { text: 'রাশিয়া', isCorrect: false },
      { text: 'জাপান', isCorrect: true },
      { text: 'পারস্য', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'মস্কাও শহরে লেখক কোন জাতির মধ্যে শিক্ষাবিস্তারের অসামান্য উদ্যোগ দেখেছিলেন?',
    answers: [
      { text: 'ইংরেজ', isCorrect: false },
      { text: 'ফরাসি', isCorrect: false },
      { text: 'রাশিয়ান', isCorrect: true },
      { text: 'জার্মান', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'রাশিয়ার শাসনে লেখক কোন দুটি ধর্মের মানুষের মধ্যে বিরোধ দেখেননি?',
    answers: [
      { text: 'হিন্দু ও বৌদ্ধ', isCorrect: false },
      { text: 'মুসলিম ও অমুসলিম', isCorrect: true },
      { text: 'খ্রিষ্টান ও ইহুদি', isCorrect: false },
      { text: 'শিয়া ও সুন্নি', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'ইংরেজ শাসনে ভারতবর্ষ কোন বিষয়ের চর্চা থেকে বঞ্চিত ছিল?',
    answers: [
      { text: 'সাহিত্য', isCorrect: false },
      { text: 'আইন', isCorrect: false },
      { text: 'যন্ত্রশক্তি', isCorrect: true },
      { text: 'ভাষা', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: "লেখক কোন দেশটিকে 'সভ্যশাসনের জগদ্দল পাথর' বুকে নিয়ে পড়ে থাকতে দেখেছেন?",
    answers: [
      { text: 'চীন', isCorrect: false },
      { text: 'আফগানিস্তান', isCorrect: false },
      { text: 'ভারতবর্ষ', isCorrect: true },
      { text: 'পারস্য', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'ইংরেজ জাতি চীনকে কিসের বিষে জর্জরিত করেছিল?',
    answers: [
      { text: 'কোকেন', isCorrect: false },
      { text: 'অহিফেন', isCorrect: true },
      { text: 'মদ', isCorrect: false },
      { text: 'তামাক', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'উত্তর-চীনকে কোন দেশ গ্রাস করতে উদ্যত হয়েছিল?',
    answers: [
      { text: 'রাশিয়া', isCorrect: false },
      { text: 'জাপান', isCorrect: true },
      { text: 'ইংল্যান্ড', isCorrect: false },
      { text: 'জার্মানি', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: "'সভ্যতার সংকট' প্রবন্ধে স্পেনের কোন সরকারের কথা উল্লেখ আছে?",
    answers: [
      { text: 'রাজতন্ত্র', isCorrect: false },
      { text: 'প্রজাতন্ত্র', isCorrect: true },
      { text: 'একনায়কতন্ত্র', isCorrect: false },
      { text: 'সামন্ততন্ত্র', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: "ভারতবর্ষের বাইরে কোথায় 'নৃশংস আত্মবিচ্ছেদ' দেখা যায় না বলে লেখক দাবি করেছেন?",
    answers: [
      { text: 'ইংল্যান্ডে', isCorrect: false },
      { text: 'জাপানে', isCorrect: false },
      { text: 'মুসলিম স্বায়ত্তশাসন-চালিত দেশে', isCorrect: true },
      { text: 'চীনে', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'লেখকের মতে, ভারতবাসীর বুদ্ধিসামর্থ্য কোন জাতির চেয়ে কম নয়?',
    answers: [
      { text: 'ইংরেজ', isCorrect: true },
      { text: 'জাপানি', isCorrect: false },
      { text: 'রাশিয়ান', isCorrect: false },
      { text: 'আমেরিকান', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: "'সোভিয়েট রাশিয়া' কাদের শক্তিমান করে তোলার চেষ্টা করেছিল?",
    answers: [
      { text: 'ধনী বণিকদের', isCorrect: false },
      { text: 'মরুচর মুসলমান জাতিকে', isCorrect: true },
      { text: 'ইংরেজদের', isCorrect: false },
      { text: 'জমিদারদের', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'পারস্য দেশ কোন দুই ইউরোপীয় জাতির চাপে পিষ্ট হচ্ছিল?',
    answers: [
      { text: 'ফরাসি ও জার্মান', isCorrect: false },
      { text: 'ইংরেজ ও রুশ', isCorrect: true },
      { text: 'স্প্যানিশ ও পর্তুগিজ', isCorrect: false },
      { text: 'ওলন্দাজ ও ইংরেজ', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'কোন দেশটি আজও ইউরোপীয় জাতির দ্বারা অভিভূত হয়নি?',
    answers: [
      { text: 'ভারত', isCorrect: false },
      { text: 'আফগানিস্তান', isCorrect: false },
      { text: 'চীন', isCorrect: false },
      { text: 'জাপান', isCorrect: true },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'লেখকের মতে, মানুষের মধ্যে যা শ্রেষ্ঠ তা কীসের মধ্যে বদ্ধ হতে পারে না?',
    answers: [
      { text: 'ধর্মের', isCorrect: false },
      { text: 'জাতির', isCorrect: false },
      { text: 'সংকীর্ণতার', isCorrect: false },
      { text: 'খ ও গ উভয়ই', isCorrect: true },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: "'সভ্যতার সংকট' প্রবন্ধটির শেষে লেখক কার জয়ের কথা বলেছেন?",
    answers: [
      { text: 'বিজ্ঞানের', isCorrect: false },
      { text: 'রাজনীতির', isCorrect: false },
      { text: 'মহৎ মানবের', isCorrect: true },
      { text: 'যন্ত্রের', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'প্রবন্ধটির শেষ কবিতাংশটিতে কার আগমনের কথা বলা হয়েছে?',
    answers: [
      { text: 'ত্রাণকর্তা', isCorrect: false },
      { text: 'মহামানব', isCorrect: true },
      { text: 'রাজা', isCorrect: false },
      { text: 'ঈশ্বর', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: "'জয় জয় জয়' ধ্বনিটি কার উদ্দেশ্যে দেওয়া হয়েছে?",
    answers: [
      { text: 'বিশ্ব বিধাতা', isCorrect: false },
      { text: 'অপরাজিত মানুষ', isCorrect: true },
      { text: 'ব্রিটিশ রাজ', isCorrect: false },
      { text: 'ভারতমাতা', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'এই ভাষণটি কোন বঙ্গাব্দে প্রদত্ত হয়েছিল?',
    answers: [
      { text: '১৩৪৮', isCorrect: true },
      { text: '১৩৫০', isCorrect: false },
      { text: '১৩৪৫', isCorrect: false },
      { text: '১৩৫২', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: "রবীন্দ্রনাথের দৃষ্টিতে 'সদাচার' প্রথার ভিত্তি কী ছিল?",
    answers: [
      { text: 'যুক্তি', isCorrect: false },
      { text: 'বিজ্ঞান', isCorrect: false },
      { text: 'কুসংস্কার ও নিষ্ঠুরতা', isCorrect: true },
      { text: 'ভালোবাসা', isCorrect: false },
    ],
  },
  {
    level: '0.4',
    subject: 'Bengali',
    questionText: 'প্রবন্ধের শেষে লেখক কোন দিগন্তে আলো দেখার কথা বলেছেন?',
    answers: [
      { text: 'উত্তর', isCorrect: false },
      { text: 'দক্ষিণ', isCorrect: false },
      { text: 'পূর্ব', isCorrect: true },
      { text: 'পশ্চিম', isCorrect: false },
    ],
  },
];
